-- ------------------------------------------------
-- Version: v1.10
--
-- Description: Migration that introduces the standard table
-- -------------------------------------------------

CREATE TABLE k_Standard (
    IDSTD integer,
    lodSTD character varying(255) NOT NULL,
    STD character varying(255),
    labelStandard character varying(255),
    descStandard text,
    lodTST character varying(255) NOT NULL,
    lodSTD_V character varying(255),
    startDate timestamp with time zone,
    populatedBy character varying(255),
    lastTouch character varying(255),
    PRIMARY KEY (lodSTD),
    FOREIGN KEY (lodTST) REFERENCES k_Type_Standard(lodTST) ON DELETE CASCADE
);

INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:03C5D7F5', NULL, 'SRA Scheme Internal Standard', 'The SRA accession system is part of the larger Bioinformatics Data Management Systems used by the NCBI to manage, archive, and share genomic sequence data.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:03C5D7F5X', NULL, 'None', 'No specific standard is known for this identifier. If yiou have information on the standard, please contact us via the helpdesk button (bottom right)', 'None', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:08650BA9', NULL, 'Genome ID Standard', 'The Genome ID is  an internal identifier specific to the database or system in which it is used, such as NCBI’s Genome Database. The system for assigning GI numbers was developed by NCBI to manage the large amount of sequence data in its repositories, and', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:08ED4B63', NULL, 'Finnish Business Information Act', 'A business identity code means a code, consisting of a consecutive number and a control number, given to each party liable to register and by which the party can be identified.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0C1DF6E0', NULL, 'ISO 3297:2022', 'International Standard Serial Number', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0D1FD2AD', NULL, 'dbSNP Standard', 'The rsID is part of the dbSNP (Database of Single Nucleotide Polymorphisms) database, and its use is standardized within this context.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:11C24D84', NULL, 'The Resource Identification Initiative', 'RRIDs represent accession numbers assigned by an authoritative database, e.g., the model organism databases, for each type of resource.', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1426D6CA', NULL, 'ISO 7064', 'ISO 7064 is a standard that specifies a system for checking the validity of identification numbers using a modular arithmetic checksum. ', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:155292FA', NULL, 'GEO ID Standard', 'The GEO ID scheme is an internal identifier system specific to the NCBI''s GEO database. The identifiers are designed to be unique within the GEO system and provide a structured way to reference and access different types of genomic data.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2323CE54', NULL, 'Internal ARK Alliance Standard', 'In process of being standardised', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:24003AD9', NULL, 'DID Specification Registries', 'DIDs are URIs that associate a DID subject with a DID document.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2D1EACFC', NULL, 'INSDC Accession Prefix Format', 'The accession assignment process is managed within the collaboration to ensure accession numbers are unique by allotting accession prefixes to individual members.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2FF46922', NULL, 'ISO 2108:2017', 'ISO 2108:2017 establishes the specifications for the International Standard Book Number (ISBN) as a unique international identification system for each product form or edition of a separately available monographic publication published or produced by a sp', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3174D6ED', NULL, 'GeoNames Identifier Standard', 'The Geonames ID is a proprietary identifier system created and used specifically within the GeoNames database.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:37CF6252', NULL, 'Structure of the LC Control Number', 'The LCCN is a well-established de facto national standard in the United States, used primarily by the Library of Congress.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3BA1C753', NULL, 'TaxID Standard', 'The TaxID is widely accepted as a de facto standard within the biological and bioinformatics communities due to its extensive use in NCBI’s suite of databases, but is not a publushed standard.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3FC02968', NULL, 'SF-edu-ID Standard', 'The SF-edu-ID is based on internal standards specific to the Swiss educational system. While it aligns with broader principles of identity management and unique identifiers in educational contexts.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:41989AD1', NULL, 'ISLRN Standard', 'The ISLRN is not based on an international standard but was developed specifically for the language resources community to ensure that these resources can be consistently referenced', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:46349C90', NULL, 'Gene ID Standard', 'The Gene ID is an internal identifier specific to the NCBI Gene database. It is widely recognised within the bioinformatics and genomics communities, but is not governed by an external standards organisation', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4B0E49ED', NULL, 'PMCID Standard', 'The PMCID is not based on an external, internationally recognised standard such as DOI, ISBN, or ISSN. However, it functions similarly to these identifiers in that it provides a persistent, unique reference to an article within the PubMed Central system.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4E83F34B', NULL, 'MMDB-ID Standard', 'The MMDB-ID is an internal identifier used specifically within the NCBI''s MMDB, and is based on an internal standard.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:519CC809', NULL, 'RFC 2396: Uniform Resource Identifiers (URI): Generic Syntax', 'This paper describes a "superset" of operations that can be applied to URI.  It consists of both a grammar and a description of basic functionality for URI.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:58116CCC', NULL, 'PopSet ID Standard', 'The PopSet ID is not based on any external, internationally recognised standard like DOI, ISBN, or ISSN. Instead, it is an internal identifier specific to the NCBI’s PopSet database. It is used to uniquely identify and access collections of related geneti', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:59FE1DE9', NULL, 'Ringgold Standard', 'While it is widely used by publishers, libraries, and other entities to manage institutional affiliations and metadata, it remains an internal standard rather than a global standard.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6D76EE18', NULL, 'IMDB Data Key Concepts', 'IMDb uses unique identifiers for each of the entities referenced in IMDb data. For example "Name IDs" identify name entities (people) and "Title IDs" identify title entities (movies, series, episodes and video games).', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:718EC1D6', NULL, 'Virta-Id Standard', 'The Virta-ID is based on internal standards specific to the VIRTA system, which is a part of Finland’s national research information infrastructure.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:737A5D64', NULL, 'SID Standard', 'The SID is an internal identifier specific to the PubChem database, designed to uniquely identify substances within that system, and is an internal standard.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:78116557', NULL, 'HAL Article Identifier Standard', 'The HAL Article Identifier itself is not directly based on an international standard, but it follows a system specific to the HAL repository', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7A71E8B7', NULL, 'PMID Standard', 'The PMID is an internal identifier specific to the PubMed database. While it functions as a persistent and unique identifier within PubMed, it is not governed by an external standards organisation. The PMID is widely accepted within the medical and scient', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7BE009A6', NULL, 'IMDB Data Key Concepts', 'IMDb uses unique identifiers for each of the entities referenced in IMDb data. For example "Name IDs" identify name entities (people) and "Title IDs" identify title entities (movies, series, episodes and video games).', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7C7BC94D', NULL, 'RFC 8141: Uniform Resource Names (URNs)', 'A Uniform Resource Name (URN) is a Uniform Resource Identifier (URI that is assigned under the "urn" URI scheme and a particular URN namespace, with the intent that the URN will be a persistent, location-independent resource identifier.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:82EFCA7C', NULL, 'Protein Cluster Identifier Standard', 'The Protein Cluster ID is an internal identifier used specifically within the NCBI''s protein cluster database. The ID is designed to uniquely identify and catalog protein clusters', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:85BABC2C', NULL, 'ISO 3901 - ISRC Standard', 'The ISRC system is internationally standardized and is part of the International Standard for Sound Recordings and Music Videos, defined by ISO 3901.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:85FC6BE0', NULL, 'JuFo-Id Standard', 'The JuFo-ID is not based on an internationally recognised standard such as DOI, ISBN, or ISSN. It is an internal identifier specific to the Finnish Publication Forum. The identifier is used within Finland’s academic evaluation system to assess and classif', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8DB69A38', NULL, 'PSSM ID Standard', 'PSSM ID is based on an internal identifier specific to NCBI’s systems. The PSSM ID is used to uniquely identify PSSMs within the NCBI''s protein databases, particularly within the context of tools like PSI-BLAST.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8E37FD4E', NULL, 'dbGaP PD Standard', 'The dbGaP ID is an internal identifier specific to the NCBI’s dbGaP database, designed to uniquely identify and track genotypic and phenotypic data within the database.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:924940FD', NULL, 'Internal British National Archives Standard - ARCHON', 'The ARCHON identifier is an internal standard specific to The National Archives and its directory of archives.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:93994055', NULL, 'Scopus Author ID Standard', 'The Scopus Author ID is an internal identifier specific to the Scopus database, developed by Elsevier.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9DEADEA4', NULL, 'dbVar ID Standard', 'The dbVar ID is an internal identifier specific to the NCBI’s dbVar database, designed to uniquely identify and manage structural variation data within the database.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6DD5C860', NULL, 'Bibcode Published Schema', 'The bibcode is a 19 digit identifier which describes the journal article. The format was originally adopted by the SIMBAD and NED projects', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6DD5C860KK', NULL, 'InChI Certification Suite', '... a software package developed and designed to check that an installation of the InChI program has been performed correctly. The certification programs test the installation against a broad set of structures (which are provided with the suite package).', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6DD5C860KL', NULL, 'ISO 27729:2012', 'ISO 27729:2012 specifies the International Standard name identifier (ISNI) for the identification of public identities of parties, i.e. the  identities used publicly by parties involved throughout the media content industries in the creation, production, ', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6DD5C860KM', NULL, 'LSID (Life Science Identifier)', 'The LSID standard is maintained and governed by the International Organization for Standardisation (ISO) as part of ISO/IEC standards. However, it was originally proposed and widely promoted by the Global Biodiversity Information Facility (GBIF) and Taxon', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6DD5C860KN', NULL, 'Standard for Z39.88-2004', 'Z39.88-2004 provides a framework for creating unique and permanent identifiers for digital objects. These identifiers are designed to be stable over time and ensure that resources can be consistently referenced.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6DD5C860Y', NULL, 'Internal WOS Accession Number Standard', 'A unique academic work identifier assigned in Web of Science bibliographic database', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6DD5C860Z', NULL, 'VIAF Standard', 'The VIAF system operates as a collaborative project that integrates authority data from various national libraries and other institutions, making it a de facto standard within the library and information science community for linking authority data across', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A8A98608', NULL, 'Handle System Protocol (ver 2.1) Specification', 'The Handle System is a general-purpose global name service that allows secured name resolution and administration over the public Internet.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AACA3EAD', NULL, 'GRID Standard', 'The GRID identifier is not based on an international identifier standard - it is a proprietary identifier developed specifically for use within the GRID database to uniquely identify research institutions.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B0CA7BF7', NULL, 'GDS ID Standard', 'The GDS ID is an internal identifier specific to NCBI''s GEO database.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B47A7A965', NULL, 'Wikidata Identifiers Standard', 'The Q and P identifiers used in Wikidata are not based on any external, internationally recognised standard. They are unique to Wikidata and are part of its internal system for managing and linking data. However, Wikidata''s identifiers is widely used in t', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BB9EEC03', NULL, 'ResearcherID Standard', 'The ResearcherID is a proprietary identifier developed by Clarivate Analytics for use within its suite of research analytics tools, using an internal standard.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BDB801FE', NULL, 'NCBI Internal Standard - CID', 'The PubChem Compound Accession identifier (CID) is maintained by the', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BF7F2596', NULL, 'ISSN Manual', 'The International Standard Serial Number (ISSN) was developed in the early 1970’s by the International Organization for Standardization (ISO) in order to meet the need for a brief, unique and unambiguous identification code for serial publications.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C13D7653', NULL, 'INSDC Accession Prefix Format', 'The accession assignment process is managed within the collaboration to ensure accession numbers are unique by allotting accession prefixes to individual members.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C4194F37', NULL, 'ANSI/NISO Z39.88-2004 The OpenURL Framework for Context-Sensitive Services', 'The OpenURL Framework Standard defines an architecture for creating OpenURL Framework Applications. An OpenURL Framework Application is a networked service environment, in which packages of information are transported over a network.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C4812562', NULL, 'ULAN Standard', 'The ULAN ID is not based on an external, internationally recognised standard such as DOI, ISBN, or ISSN. However, it follows the principles of controlled vocabularies and identifiers within the cultural heritage and library communities. The ULAN ID functi', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:CE5ABC88', NULL, 'HomoloGene ID Standard', 'Not based on any standard -  internal identifier used specifically within the NCBI (National Center for Biotechnology Information) to uniquely identify groups of homologous genes across different species.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D20A7975', NULL, 'ICD-11 Implementation or Transition Guide', 'Each ICD11 entity has an exclusive identity linked to a Uniform Resource Identifier (URI) and back-end web services to provide easy access to up-to-date ICD content. ICD is based on a globally recognised standard maintained by the World Health Organizatio', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D6856C2B', NULL, 'Probe ID Standard', 'The Probe ID is an internal identifier specific to the NCBI''s Probe database. It is designed to uniquely identify probe sequences within the context of the NCBI’s bioinformatics resources.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DF407A05', NULL, 'GePRIS Standard', 'The GEPRIS Historisch ID is a unique identifier assigned to individuals within the GEPRIS Historisch database, which documents historical research projects funded by the Deutsche Forschungsgemeinschaft (DFG). This identifier is specific to the GEPRIS Hist', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E0290620', NULL, 'ISO 26324:2022', '... defines the syntax for a DOI name, which is used for the identification of an object of any material form (digital or physical) or an abstraction (such as a textual work) where there is a functional need to distinguish it from other objects. The DOI ', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E2530971', NULL, 'Internal NCBI Standard - AID', 'The AID is an internal standard specific to the BioAssay database.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:EF341ECC', NULL, 'RFC 3987: Internationalized Resource Identifiers (IRIs)', 'This document defines a new protocol element, the Internationalized Resource Identifier (IRI), as a complement to the Uniform Resource Identifier (URI).  An IRI is a sequence of characters from the Universal Character Set (Unicode/ISO 10646).', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F31F9CAA', NULL, 'PIC Standard', 'The PIC ID follows the EU''s internal standards for identifying and managing participants in its funding programs. The PIC ID is an internal identifier used within the EU’s participant portal and associated systems to track and manage organisations partici', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F3C1337F', NULL, 'ISO 15511:2019', 'Information and documentation — International standard identifier for libraries and related organizations (ISIL)', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F8CE087C', NULL, 'NLM Catalogue ID Standard', 'The NLM Catalog ID is a proprietary identifier specific to the NLM’s internal systems for cataloging and managing its vast collection of biomedical literature and other resources', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F9C11242', NULL, 'UPC/ EAN Standard', 'Automatic identification and data capture techniques — EAN/UPC bar code symbology specification', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FCDAACDB', NULL, 'arXiv Internal Standard', 'The arXiv identifier does not conform to the DOI standard or any other ISO standards for unique identifiers. It is a custom system developed specifically for the arXiv repository.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FDD1477C', NULL, 'Extensible Resource Identifier (XRI) Resolution Version 2.0', 'The XRI scheme is based on a formal standard developed and approved by OASIS (Organisation for the Advancement of Structured Information Standards). Standardization Details: Developed by: OASIS XRI Technical Committee. Standard Approval: The XRI Syntax an', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FF6511FC', NULL, 'IdRef – Identifiers and References for the ESR', 'Both IdRef IDs and SUDOC IDs are proprietary identifiers used specifically within the French academic and bibliographic systems, and is based on an internal standard.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:H0C28F52C', NULL, 'MeshID Standard', 'MeshID is a specific identifier within the MeSH vocabulary system, which is a controlled vocabulary standard developed and maintained by the National Library of Medicine (NLM).', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WC92A0EAA', NULL, 'SoftWare Heritage persistent IDentifiers (SWHIDs) Standard', 'A SWHID consists of two separate parts, a mandatory *core identifier* that can point to any software artifact (or "object") available in the Software Heritage archive, and an optional list of *qualifiers* that allows to specify the context where the objec', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:Z90BFDFCF', NULL, 'GS1 General Specifications', 'The GS1 General Specifications is the core standards document of the GS1 system describing how GS1 barcodes and identification keys should be used.', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W1D686DE0', NULL, 'Internal NCBI Standard', 'Managed by NCBI (U.S. National Library of Medicine, NIH) GI numbers were internally assigned and managed by NCBI. They were used in GenBank, RefSeq, and related biological databases.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W23A41E1C', NULL, 'NZBN Internal Standard', 'NZBN is a government-mandated standard rather than a formal international standard. It is defined through New Zealand legislation and administrative guidelines rather than through an external standards body.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W328F6EF4', NULL, 'Internal OCLC Standard', 'Managed by OCLC: OCNs are assigned by OCLC, an international library cooperative. The identifier is used by libraries, publishers, and cataloging systems for bibliographic linking.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W499F787A', NULL, 'Internal Korea NRF Standard', 'National Standard: The Unique Identification Numbers are part of South Korea''s national R&D management framework.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W6FDD4602', NULL, 'Internal SBN Standard', 'While the SBN/ICCU identifiers are crucial for the management and cataloging within Italian libraries, they are not linked to an international standards body such as the International Organization for Standardization (ISO). However, the ICCU aligns its ca', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W7A91BFBD', NULL, 'CURIE Syntax 1.0', 'W3C Standard: CURIEs are defined by the World Wide Web Consortium (W3C) in the  CURIE Syntax 1.0 (W3C Recommendation, 2010)', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W8E56E057', NULL, 'Internal Korea NRF Standard', 'The National Researcher Number is a national administrative identifier specific to South Korea.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WB42981E3', NULL, 'RFC 8458: ‘Using National Bibliography Numbers as Uniform Resource Name’', 'IETF published RFC 8458, ‘Using National Bibliography Numbers as Uniform Resource Name’. It is an informational RFC which complements information provided in the URN:NBN namespace registration ', 'Published', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WD1D9B47F', NULL, 'Internal EU Standard', 'The EU PIC is not governed by an ISO or W3C standard but is an EU administrative identifier managed by the European Commission.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Standard(IDSTD, lodSTD, STD, labelStandard, descStandard, lodTST, lodSTD_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WFD91A16D', NULL, 'ISO 10957:2021', 'ISO Standard (ISO 10957:2009) ISMN is governed by the International Organization for Standardization (ISO) under ISO 10957:2009. Ensures uniqueness and persistence in identifying music publications. URN Namespace Registration (IETF RFC 3044) The URN:ISM', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');

