-- ------------------------------------------------
-- Version: v1.14
--
-- Description: Migration that introduces the scheme table
-- -------------------------------------------------

CREATE TABLE k_Scheme (
    IDSCH integer,
    lodSCH character varying(255) NOT NULL,
    SCH character varying(255),
    labelScheme character varying(255),
    descScheme text,
    lodTSC character varying(255) NOT NULL,
    lodSCH_V character varying(255),
    startDate timestamp with time zone,
    populatedBy character varying(255),
    lastTouch character varying(255),
    PRIMARY KEY (lodSCH),
    FOREIGN KEY (lodTSC) REFERENCES k_Type_Scheme(lodTSC) ON DELETE CASCADE
);


INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:30823C63', NULL, 'AID Scheme', 'The AID is an internal scheme specific to the PubChem database.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4472D271', NULL, 'ARCHON Code', 'Unique number used to identify archival collection locations within the UK and key global repositories holding collections relating to British history', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D662BC92', NULL, 'ARK Scheme', 'ARK Identifier Scheme', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D1879DD9', NULL, 'ArXiv Scheme', 'The canonical form of identifiers from January 2015 (1501) is arXiv:YYMM.NNNNN, with 5-digits for the sequence number within the month.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:640D4ED9', NULL, 'BibCode Scheme', 'The bibcode (also known as the refcode) is a compact identifier used by several astronomical data systems to uniquely specify literature references', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:39361CEE', NULL, 'Catalogue of Life ID', 'With the migration to the new infrastructure in December 2020, Catalogue of Life has also switched to a new algorithm to generate stable identifiers for name usages.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:466E3789', NULL, 'dbGaP Scheme', 'The dbGaP ID (Database of Genotypes and Phenotypes Identifier) is a unique alphanumeric identifier assigned to studies, datasets, and other entities within the NCBI’s dbGaP database. The dbGaP ID scheme typically consists of a prefix followed by a numeric', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:178B2B54', NULL, 'dbSNP Scheme', 'The rs number (Reference SNP ID), commonly known as an rsID, is a unique numeric identifier assigned to single nucleotide polymorphisms (SNPs) and other variations in the human genome. The scheme for encoding the rsID is straightforward: it consists of th', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2931A1E7', NULL, 'dbVar Scheme', 'The dbVar ID is a unique alphanumeric identifier assigned to structural variation data in the NCBI''s dbVar database. This database focuses on genomic structural variations, such as insertions, deletions, and duplications, across different organisms. The ', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0328E1A2', NULL, 'Decentralized Identifier', 'Identifier that enables a verifiable, decentralized digital identity.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:12A44A8C', NULL, 'Digital Object Identifier', 'ISO standard unique string identifier for a digital object', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DA568C41', NULL, 'European Article Number', 'The European Article Number (often shortened to EAN) is a standard to encode product numbers', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:36BB5704', NULL, 'Extensible Resource Identifier', 'An Extensible Resource Identifier (XRI) is a scheme and resolution protocol for abstract identifiers compatible with Uniform Resource Identifiers (URI) and Internationalized Resource Identifiers (IRI), developed by the XRI Technical Committee at OASIS (cl', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4C46BEFA', NULL, 'Finnish Business ID', 'In Finland, a code given to businesses and organisations. ', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D0AB5F8E', NULL, 'GDS Scheme', 'The GDS ID (Gene Expression Omnibus DataSet Identifier) is a unique numeric identifier used to reference specific datasets within the NCBI Gene Expression Omnibus (GEO) database. These datasets represent collections of gene expression data submitted by re', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:43E0801D', NULL, 'Gene ID Scheme', 'The Gene ID is a unique numeric identifier used by the NCBI (National Center for Biotechnology Information) to identify gene records in their Gene database. The scheme for encoding Gene IDs involves assigning a sequential number to each gene as it is adde', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D098CF78', NULL, 'Genome Scheme', 'The Genome ID in the NCBI Genome Database is a numeric identifier. It is assigned sequentially to each genome record, providing a unique reference for each genome stored in the database. The identifier is purely numeric and can range in length depending o', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F3F4E766', NULL, 'GEO ID Scheme', 'GEO IDs can represent different types of entities within the GEO database, such as datasets, platforms, series, and samples. Each type of GEO ID has its own prefix and numeric scheme: GSE (GEO Series ID): Represents a series, which is a collection of rel', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:761FF97D', NULL, 'GeoNames Scheme', 'The Geonames ID is a unique numeric identifier assigned to geographical entities in the GeoNames database. The identifier is a simple sequence of digits that is assigned sequentially to each new geographic entity (such as cities, countries, lakes, mountai', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D7DE5F6A', NULL, 'GePRIS Scheme', 'The GEPRIS Historisch ID is a unique identifier assigned to individuals within the GEPRIS Historisch database, which documents historical research projects funded by the Deutsche Forschungsgemeinschaft (DFG). This identifier is specific to the GEPRIS Hist', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E2C5B025', NULL, 'GRID Scheme', 'The GRID (Global Research Identifier Database) identifier is a unique alphanumeric string used to identify research-related organizations globally. The identifier typically follows the format GRID.xxxxx.x, where: GRID. is the prefix indicating the identi', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3BBE45EB', NULL, 'HAL Article Identifier Scheme', 'Identifier for an article in the HAL (Hyper Articles en Ligne) open access repository. The HAL Article ID is a unique alphanumeric identifier assigned to each submission in the HAL open-access repository. The identifier typically follows the format hal-XX', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:93FE7F4F', NULL, 'Handle System', 'Technology specification for assigning, managing, and resolving persistent identifiers for digital objects and other resources on the Internet', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:X4FF650BE', NULL, 'HomoloGene Scheme', 'The scheme for encoding these identifiers is simple and consists solely of a sequence of digits. Example of a HomoloGene ID: 12345', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C2C7D9E8', NULL, 'IdRef ID Scheme', 'Identifier for authority control in the French collaborative library catalog (see also P1025). Format: 8 digits followed by a digit or "X', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D48C81A4', NULL, 'IMDB Company ID', 'The IMDb company ID is a unique alphanumeric string that starts with the prefix co followed by a sequence of digits. For example, co0043330.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:04430ACA', NULL, 'IMDB Name ID', 'The IMDb name ID is an identifier used to uniquely identify individuals (actors, directors, etc.) in the IMDb database. The format is nm followed by a sequence of digits, such as nm0000138.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D48C81A4XX', NULL, 'IMDB Title ID', 'The IMDb title ID is used to uniquely identify films, TV shows, and other types of media. The format is tt followed by a sequence of digits, such as tt0111161.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:Q7EA31451', NULL, 'InChi Scheme', 'InChI - the worldwide chemical structure identifier standard. InChI is a structure-based chemical identifier, developed by IUPAC and the InChI Trust.', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:P7EA31451', NULL, 'InChiKey Scheme', 'InChIKey is a hash-based encoding of the InChI structure-based chemical identifier, developed by IUPAC and the InChI Trust.', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A30823C63A', NULL, 'INSDC Accession Prefix Format', 'An accession number, in bioinformatics, is a unique identifier given to a DNA or protein sequence record to allow for tracking of different versions of that sequence record and the associated sequence over time in a single data repository. The Internation', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A30823C63B', NULL, 'INSDC Accession Prefix Format', 'An accession number, in bioinformatics, is a unique identifier given to a DNA or protein sequence record to allow for tracking of different versions of that sequence record and the associated sequence over time in a single data repository. The Internation', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F0A883B6', NULL, 'Integrated Authority File ID Scheme', 'Identifier for the German National Library Integrated Authority FIle. The GND ID is an alphanumeric identifier assigned to entities within the GND system. The structure of the GND ID typically consists of digits and sometimes includes alphabetic character', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C389D86F', NULL, 'International Classification of Diseases ID (ICD-10, ICD-11)', 'Identifier in the ICD catalogue codes for diseases. The ICD (International Classification of Diseases) identifier is an alphanumeric code used to classify diseases, conditions, and other health-related issues. The encoding scheme for ICD identifiers varie', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2E188FD0', NULL, 'International Standard Book Number', 'Unique numeric book identifier.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9EC02E67', NULL, 'International Standard Language Resource Number', 'The ISLRN or International Standard Language Resource Number is Persistent Unique Identifier for Language Resources.', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2B2134FD', NULL, 'International Standard Name Identifier', 'Authority file with 16-digit identifier for people and organisations', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E7315983A', NULL, 'International Standard Recording Codes', 'An ISRC is a 12-digit code assigned to a unique recording of a specific song. This “digital fingerprint” represents a recording’s distinct identity and allows the tracking of key details as sales, streams, radio station plays, and the composition’s author', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1E673A54', NULL, 'International Standard Serial Number', 'A standard code (ISSN) for the unique identification of serials and other continuing resources. Each International Standard Serial Number (ISSN) is a unique identifier for a serial or other continuing resource in a defined medium whether print or electron', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:23E424DA', NULL, 'IRI (Internationalised Resource Identifier)', 'Identifier for resources made using Unicode/ISO 10646 characters specified by RFC 3987', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:68D59A3E', NULL, 'JuFo-ID', 'The Publication Forum is a classification of publication channels created by the Finnish scientific community to support the quality assessment of academic research. The JuFo-ID is a unique numeric identifier used in the Finnish Publication Forum (Julkais', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3419AB81', NULL, 'LCCN Scheme', 'Numbering system for catalog records at the Library of Congress (not a subject classification). The LCCN (Library of Congress Control Number) is a unique identifier used to catalog and track records in the Library of Congress and other libraries that use ', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:91C9EA8C', NULL, 'MeSH Scheme', 'The scheme for MeSH IDs consists of a string that can include both letters and numbers. There are two main types of MeSH IDs: Descriptor UI (Unique Identifier): Typically starts with a "D" followed by a sequence of numbers, such as D012345. Supplementary', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:758C76E6', NULL, 'MMDB Scheme', 'The MMDB-ID (Molecular Modeling Database Identifier) is a unique numeric identifier used to reference molecular structures within the NCBI''s Molecular Modeling Database (MMDB). This database contains 3D structures of proteins and other biomolecules, often', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6765D6E0', NULL, 'NLM Catalog Scheme', 'The scheme for encoding the NLM Catalog ID is a simple alphanumeric sequence, typically comprising a combination of letters and numbers. These identifiers do not follow a standardized format like those for DOI or ISBN but are generated according to NLM’s ', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:18941E49', NULL, 'None', 'No specific scheme is known for this identifier. If yiou have information on the scheme, please contact us via the helpdesk button (bottom right)', 'None', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:256A241B', NULL, 'Open Uniform Resource Locator Scheme', 'Standardised format for linking to information resources. The Z39.88-2004 Matrix Constraint Language is used to specify constraints for descriptions of resources expressed using the KEV Serialisation, which is used to construct an OpenURL.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A49AC1A1', NULL, 'PIC Scheme', 'The PIC (Participant Identification Code) is a unique 9-digit numeric identifier assigned to organisations participating in European Union (EU) funding programs. The scheme for encoding the PIC is straightforward: it is a sequence of nine digits, without ', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A1308A73', NULL, 'PMCID Scheme', 'The PMCID (PubMed Central ID) is a unique identifier assigned to articles that are archived in PubMed Central (PMC), a free digital repository of biomedical and life sciences journal literature. The PMCID is a numeric identifier prefixed with "PMC" follow', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:16297F14', NULL, 'PopSet Scheme', 'The PopSet ID is a sequential number assigned to each PopSet record as it is entered into the NCBI database. The identifier is purely numeric and serves as a unique reference to the specific set of sequences grouped together under a single study or resear', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3140D7F2', NULL, 'Probe Scheme', 'The Probe ID is a unique numeric identifier assigned to molecular probes in the NCBI Probe Database. Molecular probes are sequences of DNA or RNA that are used to detect the presence of complementary sequences by hybridization. The Probe ID is a sequentia', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4FF650BE', NULL, 'Protein Cluster Scheme', 'The Protein Cluster ID is a unique alphanumeric identifier assigned to protein clusters within the NCBI (National Center for Biotechnology Information) protein cluster database. The identifier typically follows a format that includes a prefix (usually "PR', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:737331F5', NULL, 'PSSM Scheme', 'The PSSM ID (Position-Specific Scoring Matrix Identifier) is a unique numeric identifier used within the NCBI database for referencing specific PSSMs. A PSSM is a matrix used in bioinformatics to represent motifs, particularly for protein sequences, and i', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8F0C6E1C', NULL, 'Pub Med Identification Number', 'PubMed''s Unique Identifier of a Scholarly Work. The PMID (PubMed Identifier) is a unique numeric identifier used to identify citations within the PubMed database, which is maintained by the National Center for Biotechnology Information (NCBI). The PMID is', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:560BA89B', NULL, 'PubChem CID Scheme', 'The PubChem Compound Accession identifier (CID) is maintained by the', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:82504F86', NULL, 'PubChem Substance Scheme', 'The SID (Substance ID) is a unique numeric identifier used in the PubChem database to identify specific chemical substances. Each SID corresponds to a particular substance record submitted to PubChem by a data contributor, such as chemical vendors, resear', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:53090BCF', NULL, 'RAI Scheme', 'No description', 'Unknown', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C3E6AFDE', NULL, 'Researcher ID Scheme', 'The ResearcherID is an alphanumeric identifier assigned to individual researchers to uniquely identify them within the Web of Science ecosystem and other Clarivate Analytics products. The identifier typically follows a format that includes a capital lette', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:JC7BB55BC', NULL, 'Ringgold Scheme', 'The Ringgold ID is a unique numeric identifier used to identify institutions and organizations in the academic and research sectors. The identifier is a simple integer with no alphabetic characters or special symbols, and it is assigned sequentially as ne', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7742005A', NULL, 'RRID Identifier Scheme', 'Persistent and unique identifier for referencing a research resource.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:25347D6E', NULL, 'Scheme - Z39.88-2004', 'The Z39.88-2004 scheme, also known as The Standard for the Identification of Library and Information Resources, is a standard for creating persistent identifiers for digital objects, specifically designed for bibliographic materials. It was developed to e', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0637DC80', NULL, 'Scopus Author ID Scheme', 'The Scopus Author ID is a unique numeric identifier assigned to authors in the Scopus database. The scheme for encoding these identifiers involves assigning a sequence of digits, typically 10 or more, to each author profile within the Scopus system. This ', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:CCF0A424', NULL, 'SF-edu-ID Scheme', 'The SF-edu-ID is typically an alphanumeric identifier designed to uniquely identify individuals within the Swiss educational ecosystem. The exact format may vary depending on the implementation, but it generally consists of a combination of letters and nu', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4BC70C7C', NULL, 'Software Hash ID', 'Persistent identifier of a software source code artifact as archived in the Software Heritage Archive. The SWHID encoding scheme follows a hierarchical, structured format that includes a versioned namespace, the object type, and a cryptographic hash of th', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4C9A9233', NULL, 'SRA Scheme', 'The SRA accession number scheme is not explicitly based on a formal international standard. The scheme is standardised within the context of the NCBI''s (National Center for Biotechnology Information) SRA. The SRA uses a unique accession number schema (e.g', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:08F12BD8', NULL, 'Taxonomy Database Scheme', 'The TaxID (Taxonomy Identifier) is a unique numeric identifier used to represent species or higher taxonomic groups in the NCBI Taxonomy database. The encoding scheme for TaxID is purely numeric, and each TaxID is assigned sequentially to a taxon as it is', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:736042C6', NULL, 'Uniform Resource Identifier', 'Uniform Resource Identifier (URI) that uses the urn scheme', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:115BEAF7', NULL, 'Uniform Resource Locator', 'Location of a resource', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1478CF2A', NULL, 'Union List of Artists Name''s Identifier', 'Identifier from the Getty Union List of Artist Names. The ULAN (Union List of Artist Names) ID is a unique numeric identifier assigned to each record in the ULAN database, which is a structured vocabulary containing names and biographical information abou', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B47EE531', NULL, 'Universal Product Code', 'Barcode symbology used for tracking trade items in stores.', 'Published', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9DF01134', NULL, 'VAT Scheme', NULL, 'Unknown', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:EAB7285E', NULL, 'Virta ID Scheme', 'The Virta-ID is an alphanumeric identifier that is unique to each entity (such as a publication, dataset, or researcher) within the VIRTA system. The exact format of the Virta-ID can vary depending on the type of entity it identifies, but it generally con', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:858DA223', NULL, 'Virtual International Authority File', 'Identifier for the Virtual Authority File database.  The VIAF system operates as a collaborative project that integrates authority data from various national libraries and other institutions, making it a de facto standard within the library and informatio', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:408DCE4D', NULL, 'Wikidata Identifier Scheme', 'Q Identifiers (Items): Wikidata uses Q identifiers to uniquely identify items in its database. The format is simple: it consists of the letter "Q" followed by a sequence of digits. For example, Q42 refers to the item for Douglas Adams. P Identifiers (Pro', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9F01470F', NULL, 'WOS accession number', 'A unique academic work identifier assigned in Web of Science bibliographic database', 'Internal', NULL, NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W7A91BFBD', NULL, 'CURIE Syntax 1.0', 'W3C Standard: CURIEs are defined by the World Wide Web Consortium (W3C) in the  CURIE Syntax 1.0 (W3C Recommendation, 2010)', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WD1D9B47F', NULL, 'Internal EU Scheme', 'The EU Participant Identification Code (PIC) is a 9-digit unique identifier assigned to organizations participating in EU-funded research and innovation programs, such as Horizon Europe, Horizon 2020, and Erasmus+. Format: A 9-digit numerical identifier ', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W0B542F8C', NULL, 'Internal Korea NRF Scheme', 'In South Korea, the National Research Foundation of Korea (NRF) manages research funding and assigns unique identifiers to funded projects through the Integrated R&D Information System (IRIS). Each funded project is assigned a Unique Identification Number', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WB88E1690', NULL, 'Internal Korea NRF Scheme', 'Format: While the exact format of the National Researcher Number isn''t specified in the available sources, it is a unique identifier assigned to each researcher registered in the IRIS system. Purpose: This identifier is used to manage and operate nationa', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W9C712581', NULL, 'Internal National Library of Italy Scheme', 'The Servizio Bibliotecario Nazionale (SBN), or National Library Service of Italy, assigns unique identifiers to authors and works within its bibliographic database. These identifiers are managed by the Istituto Centrale per il Catalogo Unico (ICCU), the c', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W0C40A218', NULL, 'Internal NCBI Schema', 'The GI (GenInfo Identifier) number was a unique numeric identifier assigned to nucleotide and protein sequences in the NCBI (National Center for Biotechnology Information) databases. It was used for tracking sequence records in GenBank, RefSeq, and other ', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W11DC1806', NULL, 'Internal OCLC Scheme', 'The OCLC Control Number (OCN) is a unique numeric identifier assigned to bibliographic records in the OCLC WorldCat database, which is maintained by OCLC (Online Computer Library Center). Format: A sequentially assigned integer with no fixed length (e.g.', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WDA8DAF6D', NULL, 'Internal Scheme', 'The NZBN is a 13-digit numeric identifier assigned uniquely to every business or organization registered in New Zealand. Its structure is designed to ensure uniqueness and facilitate validation (for example, via check digits), though the specific algorith', 'Internal', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W6E04EB80', NULL, 'URN:ISMN Scheme', 'ISMN Numbering Scheme: ISMN consists of 13 digits, starting with the prefix 979-0 (since 2008). Follows a structure similar to ISBN but is specifically for printed and digital sheet music.', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_Scheme(IDSCH, lodSCH, SCH, labelScheme, descScheme, lodTSC, lodSCH_V, startDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W95785C8E', NULL, 'URN:NBN', 'IETF published RFC 8458, ‘Using National Bibliography Numbers as Uniform Resource Name’. It is an informational RFC which complements information provided in the URN:NBN namespace registration. ', 'Standardised', NULL, NULL, '0000-0002-0255-5101', '04/02/2025');

