-- ------------------------------------------------
-- Version: v1.11
--
-- Description: Migration that introduces the standards body table
-- -------------------------------------------------

CREATE TABLE k_StandardsBody (
    IDSTB integer,
    lodSTB character varying(255) NOT NULL,
    STB character varying(255),
    labelStandardsBody character varying(255),
    descStandardsBody text,
    lodSTB_V character varying(255),
    populatedBy character varying(255),
    lastTouch character varying(255),
    PRIMARY KEY (lodSTB)
);


INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:00503110', NULL, 'GS1', 'GS1 is a not-for-profit, international organization developing and maintaining its own standards for barcodes and the corresponding issue company prefixes.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:054361CE', NULL, 'iMDB - Internet Movie Database', 'Online database of information related to films, television series, and video games', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0C19BBEE', NULL, 'Deutsche Forschungsgemeinschaft (DFG)', 'The administration and maintenance of the GEPRIS Historisch IDs are managed by the DFG.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:11BD7A08', NULL, 'None', 'No specific standards body is assicated wth this identifier. If yiou have information on the standards body, please contact us via the helpdesk button (bottom right)', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1E889631', NULL, 'INSDC', 'The International Nucleotide Sequence Database Collaboration (INSDC) archives nucleotide sequence data, from raw to assembled and annotated sequences, from around the world.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:207965C142', NULL, 'Ark Alliance Technical Working Group', 'The Technical Working Group (WG) oversees development and maintenance of specifications, software, and servers that support infrastructure for the ARK Alliance (ARKA) community. Examples include ARK standardization, code for counting ARKs, and global reso', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:24E3904B', NULL, 'InChi Trust', 'The InChi Trust manages the standards for InChi and for InChiKey together with IUPAC', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2A17A682', NULL, 'Federation of Finnish Learned Societies (TSV)', 'The Federation of Finnish Learned Societies, established in 1899, is a national co-operative body for learned societies in Finland. It contributes to the co-operation between learned societies, supports and develops scholarly communication and publishing,', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3A2D478A', NULL, 'ISSN International Centre', 'The CIEPS, also known as the ISSN International Centre, is an intergovernmental organization which manages at the international level the identification and the description of serial publications and ongoing resources, print and online, in any subject.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3BF14858', NULL, 'Ringgold Inc.', 'Ringgold maintains the database of organisations, manages the assignment of Ringgold IDs, and ensures that each identifier remains unique and persistent.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:429CA7F8', NULL, 'Switch', 'The SF-edu-ID is maintained by Swiss authorities in charge of education and digital identity management - Switch.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4DDAB116', NULL, 'ISO/TC 46/SC 9', 'Standardisation of information identifiers, description and associated metadata and models for use in information organizations (including libraries, museums and archives) and the content industries (including publishing and other content producers and pr', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:53CE0E02', NULL, 'NIH', 'The National Institutes of Health, US government medical research agency.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:59EEFD5A', NULL, 'NCBI', 'The National Center for Biotechnology Information advances science and health by providing access to biomedical and genomic information.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5BBC9973', NULL, 'NISO', 'The National Information Standards Organization (NISO) is a United States non-profit standards organization that develops, maintains and publishes technical standards related to publishing, bibliographic and library applications.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:755F75E4', NULL, 'National Library of Medicine (NLM)', 'NLM is responsible for the development, updating, and management of the MeSH vocabulary and the associated identifiers.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8DEA6E80', NULL, 'UK National Archives', 'Repository of archival information for the United Kingdom.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:904896D8', NULL, 'CCSD (Centre pour la Communication Scientifique Directe)', 'The Center for Direct Scientific Communication. Organisation in France promoting open access to research', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:944E57B3', NULL, 'ADS', 'The SAO/NASA Astrophysics Data System (ADS) is a digital library portal for researchers in astronomy and physics, operated by the Smithsonian Astrophysical Observatory (SAO) under a NASA grant.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:99DC935C', NULL, 'Finnish Ministry of Economic Affairs and Employment - Finnish Patent and Registration Office (PRH)', 'The Ministry of Economic Affairs and Employment (former The Ministry of Employment and the Economic) started operations on 1 January 2008. The Government Programme of Prime Minister Matti Vanhanen’s second Government, dated 19 April 2007, included a decis', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9E7BB9FC', NULL, 'ELRA', 'Founded in 1995, the ELRA Language Resources Association, is a non-profit organisation whose main mission is to make Language Resources (LRs) for Human Language Technologies (HLT) available to the community at large.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9F0F91A9', NULL, 'ISO/TC 46/SC 4', 'Standardisation of information identifiers, description and associated metadata and models for use in information organizations (including libraries, museums and archives) and the content industries (including publishing and other content producers and pr', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9FD58CA9', NULL, 'TDWG', 'Taxonomic Databases Working Group (TDWG)', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A1180017', NULL, 'Agence bibliographique de l''enseignement supérieur', 'Located in Montpellier, the bibliographic agency of higher education (Abes) is a public institution of an administrative nature (EPA), under the direct supervision of the Ministry of Higher Education and Research (MESR).', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A9571FE0', NULL, 'GeoNames Project', 'The GeoNames project maintains the Geonames ID system.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C8FDBD1F', NULL, 'World Wide Web Foundation', 'The World Wide Web Consortium is the main international standards organization for the World Wide Web.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:CCE903B0', NULL, 'OCLC', 'OCLC is a global library cooperative.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:CD515A71', NULL, 'Cornell University', 'The arXiv identifier format is maintained by Cornell University, specifically through the arXiv.org platform, which is operated by the Cornell University Library.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D31A7652', NULL, 'The Wikimedia Foundation', 'American charitable organisation.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D37D8471', NULL, 'IETF', 'The Internet Engineering Task Force (IETF), founded in 1986, is the premier standards development organization (SDO) for the Internet.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D5C5C904', NULL, 'Digital Science', 'The GRID identifier was developed and maintained by Digital Science, a technology company serving the needs of the research community. Digital Science managed the GRID database, which contained records of research institutions globally.
As of 2021, Digita', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D81D00C6', NULL, 'OASIS', 'One of the most respected, non-profit standards bodies in the world, OASIS Open offers projects—including open source projects—a path to standardization and de jure approval for reference in international policy and procurement.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D8569850', NULL, 'World Health Organisation', 'The World Health Organisation is currently responsible for revisions, and typically appoints an Expert Committee from time to time to undertake the task.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DAC9D3C5', NULL, 'Elsevier', 'The Scopus Author ID system is maintained by Elsevier, which is the company that operates the Scopus database.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DFAF4C12', NULL, 'Clarivate', 'American analytics company.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E661B1CB', NULL, 'ISO/IEC JTC 1/SC 31', 'Automatic identification and data capture techniques', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E89A7B4C', NULL, 'ANSI,  ISO/TC 46/SC 9', 'ISO 27729:2012 specifies the International Standard name identifier (ISNI) for the identification of public identities of parties', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E9F59780', NULL, 'Resource Identification Initiative', 'The Resource Identification Initiative is designed to help researchers sufficiently cite the key resources used to produce the scientific findings reported in the biomedical literature.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F029F0E1', NULL, 'Getty Research institute', 'Organisation with archives and databases for art history and provenance research.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F27B00BB', NULL, 'ISO/TC 68', 'ISO 7064 is administered by ISO Technical Committee 68 (TC 68), which focuses on Financial Services. Specifically, Subcommittee 4 (SC 4) within TC 68 deals with the standards for banking, securities, and other financial services.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FD41544A', NULL, 'NDMSO', 'The Network Development and MARC Standards Office is a center for library and information network standards and planning in the Library of Congress. Established in 1976 to provide focus for networking activities in the Library of Congress, the office was ', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:V241D2889', NULL, 'Software Heritage', 'Software Heritage is the largest public archive of software source code and associated development history, as captured by modern version control systems.', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W181A8F7B', NULL, 'European Commission (REA)', 'Maintained by the European Research Executive Agency (REA) and European Innovation Council (EIC).', NULL, '0000-0002-0255-5101', '12/12/2024');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DC6BCD65', NULL, 'ISO/TC 46', 'TC 46 is the technical committee responsible for information and documentation standards. Within TC 46, the specific subcommittee that deals with the ISRC and other related standards for the recording industry is SC 9 (Subcommittee 9), which focuses on Id', NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:W7BCAC1E0', NULL, 'National Research Foundation of Korea (NRF)', 'In South Korea, the National Research Foundation of Korea (NRF) manages researcher information through the Integrated R&D Information System (IRIS). Within IRIS, researchers are assigned a National Researcher Number', NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WD0FD0999', NULL, 'ISO/TC 46/SC 9', 'Standardisation of information identifiers, description and associated metadata and models for use in information organizations (including libraries, museums and archives) and the content industries (including publishing and other content producers and pr', NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WFDFB54D0', NULL, 'SBN', 'SBN (National Library of Italy)', NULL, '0000-0002-0255-5101', '04/02/2025');
INSERT INTO k_StandardsBody(IDSTB, lodSTB, STB, labelStandardsBody, descStandardsBody, lodSTB_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:WFF889727', NULL, 'New Zealand Companies Office', 'The scheme is developed and maintained by New Zealand government agencies (such as the New Zealand Companies Office) as part of the national business register.', NULL, '0000-0002-0255-5101', '04/02/2025');
