-- ------------------------------------------------
-- Version: v1.24
--
-- Description: Migration that introduces the property table
-- -------------------------------------------------

CREATE TABLE k_Property (
    IDTPR integer,
    lodPRP character varying(255) NOT NULL,
    labelProperty character varying(255),
    descProperty text,
    lodCanonical character varying(255),
    alternateIdentifier text,
    IDPRP_P character varying(255),
    IDPRP_V character varying(255),
    populatedBy character varying(255),
    lastTouch character varying(255),
    PRIMARY KEY (lodPRP)
);

INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A9FBA0FDF', 'Title', 'Title of a resource (such as a book, a film, a service or a website)', 'https://www.schema.org/title', 'https://www.wikidata.org/wiki/Property:P1476', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A1F7CA326', 'SubTitle', 'Subtitle of a work or resource', NULL, 'https://www.wikidata.org/wiki/Property:P1680', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AA1A73112', 'Description', 'Description og identifier use cases and other basic information', 'https://www.schema.org/description', 'https://www.wikidata.org/wiki/Q1200750', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AC3753390', 'Status', 'The status of an actor, as defined by FC4E/F-I', 'https://schema.org/status', NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A691EA902', 'Start Date', 'Time when an entity begins to exist (inception)', 'https://schema.org/dateCreated', 'https://www.wikidata.org/wiki/Property:P571', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A47174244', 'URL_Official', 'URL to the website of this item (resource)', 'https://schema.org/URL', 'https://www.wikidata.org/wiki/Property:P856', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AF36EB45A', 'URL_Reference', 'Should be used for internet URLs as references', NULL, 'https://www.wikidata.org/wiki/Property:P854', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6CB0160D', 'URL_Resolver', 'Head of URL which takes unique IDs and returns location of item. ', 'https://schema.org/identifier', 'https://www.wikidata.org/wiki/Property:P1630', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A239A3223', 'Resolution Topology', NULL, NULL, NULL, 'pid_graph:A6CB0160D', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A63D1723E', 'URL Pattern', 'Regex pattern of URL that an external ID may be extracted.', NULL, 'https://www.wikidata.org/wiki/Property:P8966', 'pid_graph:A6CB0160D', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A22366C80', 'Identifier Pattern', 'Regex describing an identifier', NULL, 'https://www.wikidata.org/wiki/Property:P1793', 'pid_graph:A6CB0160D', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A6AA1E461', 'URL_API', 'Base URL for a web service ', 'https://schema.org/WebAPI', 'https://www.wikidata.org/wiki/Property:P6269', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AFFA5E7BE', 'Performance', NULL, NULL, NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A319598A3', 'Median Life (yrs)', NULL, NULL, NULL, 'pid_graph:AFFA5E7BE', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:ABD52DCF3', 'Unresolved (%)', NULL, NULL, NULL, 'pid_graph:AFFA5E7BE', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A77302D4A', 'Preserved', NULL, NULL, NULL, 'pid_graph:AFFA5E7BE', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A4E492124', 'Count', 'Number of values of an identifier or records in a catalog', 'https://schema.org/amount', 'https://www.wikidata.org/wiki/Property:P4876', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AEDA942F5', 'Adopters', NULL, NULL, NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AA322C58D', 'AdoptionStatus', NULL, NULL, NULL, 'pid_graph:AEDA942F5', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AB97AB282', 'Disciplinary', NULL, NULL, NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AF598A8DA', 'General', NULL, NULL, NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A29645A7B', 'Long Name', NULL, NULL, 'https://www.wikidata.org/wiki/Q109408141', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A7897FA8C', 'GUPRI', 'Indication on whether an identifier is globally unique, resolvable, and persistent', NULL, NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AB7DCFFD5', 'Globally Unique', 'The identifier is globally unique', NULL, NULL, 'pid_graph:A7897FA8C', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A65FE6ACE', 'Namespace Unique', 'The identifier is locally unique within a specific namespace', NULL, NULL, 'pid_graph:A7897FA8C', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A909A5B69', 'Resolvable', 'The iderntifier is part of a service that offers resolvability, , even if in practice there are resolution failures', NULL, NULL, 'pid_graph:A7897FA8C', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A795388D5', 'Persistent', 'The identifier is designed to be persistent, even if in practice there are persistence failures', NULL, NULL, 'pid_graph:A7897FA8C', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A9FBA0FDFF', 'Identifier Type', 'Identifier type - allocated (based on a scheme), intrinsic (computed based on object properties), URL (web URL without modifications or use of a scheme) ', NULL, 'https://www.wikidata.org/wiki/Q190087', NULL, NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A8BE20C32', 'Coverage', 'The global, regional, or national coverage of the Identifier', NULL, NULL, 'pid_graph:A6AA1E461', NULL, '0000-0002-0255-5101', '30/01/2025');
INSERT INTO k_Property(IDTPR, lodPRP, labelProperty, descProperty, lodCanonical, alternateIdentifier, IDPRP_P, IDPRP_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:PA6CB0160D', 'Governance', 'The extent to which the community is involved in governance structures', NULL, NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2025');

