-- ------------------------------------------------
-- Version: v1.21
--
-- Description: Migration that introduces the resolver table
-- -------------------------------------------------

CREATE TABLE k_Resolver (
    lodRES character varying(255) NOT NULL,
    labelResolver character varying(255),
    descResolver text,
    defaultValue character varying(255),
    apiUrl character varying(255),
    httpMethod character varying(255),
    regexPattern character varying(255),
    primaryResolver character varying(255),
    curieFormat character varying(255),
    lastTouch character varying(255),
    populatedBy character varying(255),
    PRIMARY KEY (lodRES)
);

INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R37757D31', 'http://ark.bnf.fr/', 'ARKs via the Bibliothèque Nationale de France', 'N/A', NULL, '^https:\/\/ark.bnf.fr\/(ark\:)/*[0-9A-Za-z]+(?:/[\w/.=*+@\$-]*)?(?:\?.*)?$', '^(ark\:)/*[0-9A-Za-z]+(?:/[\w/.=*+@\$-]*)?(?:\?.*)?$', 'N/A', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RF8C99FF2', 'http://discovery.nationalarchives.gov.uk/details/a?_ref=', NULL, 'Yes', 'https://discovery.nationalarchives.gov.uk/API', '^https?:\/\/discovery\.nationalarchives\.gov\.uk\/details\/a\?_ref=([1-9]\d{0,3})', '[1-9]\d{0,3}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R6BEE856A', 'http://en.wikipedia.org/wiki/', 'Wikipedia (English)', 'Yes', 'https://en.wikipedia.org/w/api.php', '^https?:\/\/(?:www\.)?wikipedia\.org\/wiki/[A-Za-z-0-9_]+$', '^[A-Za-z-0-9_]+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R1A56CBB2', 'http://n2t.net', 'ARKs via Name-to-Thing', 'N/A', 'http://n2t.net', '^https:\/\/n2t.net\/(ark\:)/*[0-9A-Za-z]+(?:/[\w/.=*+@\$-]*)?(?:\?.*)?$', '^(ark\:)/*[0-9A-Za-z]+(?:/[\w/.=*+@\$-]*)?(?:\?.*)?$', 'N/A', 'Yes', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R3E699C22', 'http://nbn.depositolegale.it/', NULL, 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R15D558E5', 'http://nbn-resolving.de/', 'National Bibliography Number', 'Yes', 'http://nbn-resolving.de/', '^http?:\/\/nbn-resolving\.de\/(?i)urn:nbn:.*', '(?i)urn:nbn:.*', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R28929F85', 'http://oid-info.com/get/', 'OID Repository', 'Yes', NULL, '^https?:\/\/oid-info\.com\/get\/([0123](\.\d+)*) ', '^[\d.]+$ ', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R0B40D0C7', 'http://resolver.obvsg.at/', 'National Bibliography Number via Austrian National Library', 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RB485C907', 'http://urn.fi/', 'National Bibliography Number via National Library of Finland', 'Yes', 'http://urn.fi/', '^http?:\/\/urn.fi\/(?i)(urn:nbn:fi.+)', '(?i)(urn:nbn:fi.+)', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R94B67752', 'http://urn.kb.se/resolve?urn=', 'National Bibliography Number', 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R9125C71B', 'http://urn.nb.no/', 'National Bibliography Number via National Library of Norway', 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RE5DC52A1', 'http://viaf.org/viaf/', 'Virtual International Authority File', 'Yes', 'https://refine.codefork.com/reconcile/viaf https://iphylo.org/~rpage/phyloinformatics/services/reconciliation_viaf.php', '^https?:\/\/(?:www\.)?viaf\.org\/viaf\/([1-9]\d(?:\d{0,7}|\d{17,20}))($|\/|\?|#)', '^\d+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R33431821', 'http://www.lsid.info/resolver/', 'Life Science Identifier', 'Yes', 'http://www.lsid.info/resolver/', '^http?:\/\/www\.lsid\.info\/resolver\/(urn:lsid:([\w-\.]+\.[\w-\.]+)+:Project:\S+)|(Project:\S+)', '(urn:lsid:([\w-\.]+\.[\w-\.]+)+:Project:\S+)|(Project:\S+)', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R258C8209', 'http://xri.net/', 'Extensible Resource Identifier', 'Yes', NULL, '^http?:\/\/xri\.net\/(=|@|\+|!)(([A-Za-z0-9]+[-._]*)*[A-Za-z0-9]+(\*[A-Za-z0-9]+[-._]*)*[A-Za-z0-9]*)*(\((\d{1,5})\))?(/([A-Za-z0-9]+[-._]*)*[A-Za-z0-9]*)*$', '^(=|@|\+|!)(([A-Za-z0-9]+[-._]*)*[A-Za-z0-9]+(\*[A-Za-z0-9]+[-._]*)*[A-Za-z0-9]*)*(\((\d{1,5})\))?(/([A-Za-z0-9]+[-._]*)*[A-Za-z0-9]*)*$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R2B9D9135', 'https://archive.softwareheritage.org/', 'ID for Software Heritage Archive', 'Yes', 'https://archive.softwareheritage.org/api/1/', '^https?:\/\/archive\.softwareheritage\.org\/(swh:1:(cnt|dir|rel|rev|snp):[0-9a-f]{40}(;(origin|visit|anchor|path|lines)=\S+)*)', 'swh:1:(cnt|dir|rel|rev|snp):[0-9a-f]{40}(;(origin|visit|anchor|path|lines)=\S+)*$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R7058EDA4', 'https://arxiv.org/abs/', 'Cornell University arXiv', 'Yes', 'https://info.arxiv.org/help/bulk_data/index.html', '^https?:\/\/arxiv\.org\/abs\/(\w+(\-\w+)?(\.\w+)?)?\d{4,7}(\.\d+(v\d+)?)?$', '^(\w+(\-\w+)?(\.\w+)?)?\d{4,7}(\.\d+(v\d+)?)?$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R48F8B78F', 'https://bitbucket.org/', 'Atlassian Corporation Plc is an Australian software company that develops products for software developers, project managers and other software development teams.', 'Yes', 'https://developer.atlassian.com/cloud/bitbucket/rest/intro/#authentication', '^https:\/\/bitbucket.org\/[0-9A-Za-z-_\.]+\/[0-9A-Za-z-_\.]+$', '^[0-9A-Za-z-_\.]+/[0-9A-Za-z-_\.]+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R2BE47A37', 'https://cactus.nci.nih.gov/chemical/structure', 'InChI through NIH', 'Yes', 'https://cactus.nci.nih.gov/chemical/structure', '^https?:\/\/cactus\.nci\.nih\.gov\/chemical\/structure\/([^\/]+)\/inchi$', '^InChI=1S\/.*$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RB7AF542E', 'https://d-nb.info/gnd/', 'GND is the ID for the German National Libraries integrated authority file.', 'Yes', 'https://www.dnb.de/EN/Professionell/Metadatendienste/Datenbezug/Entity-Facts/entityFacts_node.html', '^https?:\/\/d\-nb\.info\/gnd\/(|(1[012]?\d{7}[0-9X]|[47]\d{6}-\d|[1-9]\d{0,7}-[0-9X]|3\d{7}[0-9X]))$', '1[0123]?\d{7}[0-9X]|[47]\d{6}-\d|[1-9]\d{0,7}-[0-9X]|3\d{7}[0-9X]', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R7CE999A3', 'https://dx.doi.org', 'Digital Object Identifier', 'Yes', 'https://www.doi.org/api/handles/<handle>', '^https:\/\/doi.org\/10\.\d{4,9}\/[-._;()\/:A-Z0-9]+$', '^10\.\d{4,9}\/[-._;()\/:A-Z0-9]+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R42DB2A2E', 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/how-to-participate/participant-register-search?isExactMatch=true&type=ORGANISATION&order=DESC&pageNumber=1&pageSize=50&sortBy=lastModified', 'EU Participant Identification Code', 'Yes', NULL, '^https?:\/\/ec\.europa\.eu\/info\/funding-tenders\/opportunities\/portal\/screen\/how-to-participate\/org-details\/(\d+) ', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R9B71826B', 'https://github.org/', 'GitHub, Inc. is a provider of Internet hosting for software development and version control using Git.', 'Yes', 'https://docs.github.com/en/rest/users?apiVersion=2022-11-28', '^https:\/\/identifiers\.org\/github:[a-zA-Z0-9-_]+\/[a-zA-Z0-9-_]+$', '^[a-zA-Z0-9-_]+/[a-zA-Z0-9-_]+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R98F0AF45', 'https://gitlab.com/', 'GitLab is an open core company which develops software for the software development lifecycle with 30 million estimated registered users and more than 1 million active license users, and has an active community of more than 2,500 contributors.', 'Yes', 'https://docs.gitlab.com/ee/api/users.html', '^https:\/\/identifiers\.org\/gitlab:[0-9A-Za-z_][0-9A-Za-z-_()\. ]*\/[0-9A-Za-z_][0-9A-Za-z-_\. ]*$', '^[0-9A-Za-z_][0-9A-Za-z-_()\. ]*/[0-9A-Za-z_][0-9A-Za-z-_\. ]*$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R893CB252', 'https://hal.science/', 'Hyper Articles en Ligne Article ID', 'Yes', 'http://api.archives-openes.fr/search/', '^https:\/\/(?www\.)?hal\.science\/[a-z\d]+-\d+', '[a-z\d]+-\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R970952E2', 'https://hdl.handle.net/', 'Handle is a superset of DOI, ePIC, and others', 'Yes', 'Not Available', NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R9F266D24', 'https://hdl.handle.net/', 'Handle is a superset of DOI', 'Yes', 'Global Handle Registry (GHR)', '^https?:\/\/hdl\.handle\.net\/([0-9a-z]+(?:\.[0-9a-z]+)*\/.{2,})', '^[0-9a-z]+(\.[0-9a-z]+)*\/.{2,}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RB6F97F6D', 'https://hdl.handle.net/{$id}', 'DOI via Handle.net', 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R556B4009', 'https://icd.who.int/browse/2024-01/mms/en', 'International Statistical Classification of Diseases and Related Health Problems', 'Yes', 'https://icd.who.int/icdapi', '^https:\/\/identifiers\.org\/icd:[A-Z]\d+(\.[-\d+])?$', '^[A-Z]\d+(\.[-\d+])?$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R5AC37384', 'https://identifiers.org/', 'Decentralized Identifiers (DIDs)', 'N/A', 'https://www.w3.org/TR/did-core/', '^https:\/\/identifiers\.org\/did:[a-z0-9]+:[A-Za-z0-9.\-:]+$', '^did:[a-z0-9]+:[A-Za-z0-9.\-:]+$', 'N/A', 'Yes', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R8EF6604A', 'https://ido.ringgold.com/search/results?simple=', 'Identifier for the RInggold Database', 'Yes', 'https://api.protocols.io/v1/', '^https?:\/\/ido\.ringgold\.com\/search\/results\?simple=(\d{4,6})', '\d{4,6}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RB72F15C8', 'https://isbnsearch.org/isbn/', 'International Standard Audiovisual Number', 'Yes', 'https://api.isbndb.com/book/', '^https:\/\/isbnsearch.org\/isbn\/^\d{3}-\d{1,5}-\d{1,7}-\d{1,7}-\d{1,7}$', '^\d{3}-\d{1,5}-\d{1,7}-\d{1,7}-\d{1,7}$', 'Yes', 'Yes', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R0DF31EE3', 'https://isni.org/isni/', 'International Standard Name Identifier', 'Yes', 'https://isni-m.oclc.org/DB=1.3', '^https?:\/\/(?:www\.)?isni\.org\/isni\/(\d{4})(\d{4})(\d{4})(\d{3}[\dX])$', '^[0-9]{15}[0-9X]{1}$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RD57A11D2', 'https://isrc.soundexchange.com', 'ISRC via SoundExchange', 'Yes', NULL, NULL, '(URN:ISRC:[A-Z]{2}[A-Z0-9]{3}\d{2}\d{5})', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R4D8059D5', 'https://isrcsearch.ifpi.org', 'International Federation of the Phonographic Industry (IFPI) ISRC Resolver', 'Yes', NULL, NULL, '^[A-Z]{2}[A-Z0-9]{3}\d{2}\d{5}$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R35AAB00B', 'https://jfp.csc.fi/en/web/haku/julkaisukanavahaku#!PublicationInformationView/id/', 'Finnish Publication Forum Resolver', 'Yes', 'https://jfp.csc.fi/en/web/haku/', '^https?:\/\/jfp\.csc\.fi\/en\/web\/haku\/julkaisukanavahaku#!PublicationInformationView\/id\/(\d{5})', '^\d{5}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R452B32DC', 'https://lccn.loc.gov/', 'Library of Congress Control Number', 'Yes', 'https://www.loc.gov/apis/', '^https?:\/\/id\.loc\.gov\/authorities\/(?:(?:name|subject)s\/)?((?:gf|n|nb|nr|no|ns|sh|sj)(?:[4-9][0-9]|00|20[0-2][0-9])[0-9]{6})', '^(gf|n|nb|nr|no|ns|sh|sj)([4-9][0-9]|00|20[0-2][0-9])[0-9]{6}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R94543D01', 'https://magneturi.link/', 'Magnet URIs', 'Yes', NULL, '^https?:\/\/magneturi\.link\/\?xt=urn:[a-zA-Z0-9]+:[a-zA-Z0-9]+(&dn=[^&]*)?(&tr=[^&]*)?(&[a-zA-Z0-9]+=[^&]*)*$', '^urn:[a-zA-Z0-9]+:[a-zA-Z0-9]+$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R75DE81B0', 'https://nbn-resolving.org/', 'National Bibliography Number', 'Yes', 'https://nbn-resolving.org/', '^http?:\/\/nbn-resolving\.org\/(?i)urn:nbn:.*', '(?i)urn:nbn:.*', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R97EE5381', 'https://opac.sbn.it/en-US/voci-controllate-nomi', 'Servizio Bibliotecario Nazionale (SBN)', 'Yes', 'https://opac.sbn.it/risultati-ricerca-avanzata?item:5032:BID=$1', '^https?:\/\/opac\.sbn\.it\/opacsbn\/opac\/iccu\/scheda_authority\.jsp\?bid=(\D{2}[A-Z0-3]V\d{6})', '\D{2}[A-Z0-3]V\d{6}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R94A262A0', 'https://orcid.org/', 'ORCID at Bethesda', 'Yes', 'https://refine.codefork.com/reconcile/orcid, https://pub.orcid.org/resources/swagger.json', '^https?:\/\/orcid\.org\/\d{4}-\d{4}-\d{4}-\d{3}(\d|X)$', '^\d{4}-\d{4}-\d{4}-\d{3}(\d|X)$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R3C16BAE8', 'https://portal.issn.org/', 'International Standard Serial Number Portal', 'Yes', 'https://portal.issn.org/node/170', '^https://portal.issn.org/resource/ISSN/\d{4}-\d{4}$', '^\d{4}-\d{4}$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RDA3F8D57', 'https://portal.issn.org/resource/ISSN/', 'ISSN Portal', 'Yes', 'https://portal.issn.org/', '^https?:\/\/(?:portal\.)?issn\.org\/resource\/(issn|ISSN)\/([0-9]{4}-[0-9]{3}[0-9X])', '^\d{4}-\d{3}[\dX]$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R7C150A8C', 'https://pubchem.ncbi.nlm.nih.gov/bioassay/', 'PubChem Bioassay DB Accession Number', 'Yes', 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/classification/', '^https:\/\/pubchem\.ncbi\.nlm\.nih\.gov\/bioassay\/(\d+)', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R23025398', 'https://pubchem.ncbi.nlm.nih.gov/classification/#hid=', 'PubChem Compound DB Accession Number', 'Yes', 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/', '^https:\/\/pubchem\.ncbi\.nlm\.nih\.gov\/classification\/#hid=(\d+)', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R7BF49500', 'https://pubchem.ncbi.nlm.nih.gov/substance/', 'PubChem Substance DB Accession Number', 'Yes', 'https://pubchem.ncbi.nlm.nih.gov/rest/pug/substance/', '^https:\/\/pubchem\.ncbi\.nlm\.nih\.gov\/substance\/(\d+)', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RC52180B3', 'https://pubmed.ncbi.nlm.nih.gov/', 'PubMed via NCBI', 'Yes', NULL, '^https?:\/\/pubmed\.ncbi\.nlm\.nih\.gov\/(\d+)\/?', '([1-3]\d{7}|[1-9]\d{0,6})', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R7E8ECC16', 'https://purl.archive.org/', 'Persistent Uniform Resource Locator', 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R6D2EDC33', 'https://raid.org/prefix/suffix', 'RAID via CSIRO', 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RDC43E39A', 'https://ror.org/', 'Research Organization Registry', 'Yes', 'https://ror.org/tags/api/', '^https:\/\/ror.org\/0[a-hj-km-np-tv-z|0-9]{6}[0-9]{2}$', '^0[a-hj-km-np-tv-z|0-9]{6}[0-9]{2}$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RE32E1871', 'https://scicrunch.org/resolver/', 'Research Resource Identifier', 'Yes', 'https://api.scicrunch.io/elastic/v1/_cat/aliases', '^https?:\/\/scicrunch\.org\/resolver\/(RRID:(?:CVCL_[0-9A-Z]{4}|SCR_\d{6}|ab_\d{7}|IMSR_JAX:\d{6}))', 'RRID:(CVCL_[0-9A-Z]{4}|SCR_\d{6})', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R369A4FAE', 'https://search.worldcat.org/title/', NULL, 'Yes', 'https://metadata.api.oclc.org/worldcat/manage/bibs/', '^https?:\/\/(?:www\.)?worldcat\.org\/oclc\/(\d+) ', '\d{1,14}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RD6229772', 'https://tietopalvelu.ytj.fi/', 'Business and Community Information System Resolver', 'Yes', 'https://www.ytj.fi/en/index.html', '^https?:\/\/www\.ytj\.fi\/[a-z]+\/[a-z]+\/\?b=[0-9]{7}-[0-9]$', '^[0-9]{7}-[0-9]$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R421A41C3', 'https://ui.adsabs.harvard.edu/abs/', NULL, 'Yes', 'https://ui.adsabs.harvard.edu/help/api/', '^https?:\/\/ui\.adsabs\.harvard\.edu\/abs\/\d{4}[A-Za-z\.\&]{5}[\w\.]{4}[ELPQ-Z\.][\d\.]{4}[A-Z]$', '^(\d{4}[A-Za-z\.\&]{5}[\w\.]{4}[ELPQ-Z\.][\d\.]{4}[A-Z])$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RE9CD7FBB', 'https://ui.eidr.org/search', 'Unique Identifier system for media content.', 'Yes', 'https://www.eidr.org/technical-documentation/', '^https:\/\/ui.eidr.org\/view\/content?id=10\.5240/([0-9A-Z]{4}-){5}[0-9A-Z]', '^10\.5240/([0-9A-Z]{4}-){5}[0-9A-Z]$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R8C7DE125', 'https://uniresolver.io/', 'Decentralized Identifiers (DIDs)', 'N/A', NULL, NULL, NULL, 'N/A', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R35AB3459', 'https://w3id.org/', 'World Wide Web Consortium ID', 'Yes', NULL, '^https?:\/\/w3id\.org\/*', '*', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R6C247A41', 'https://w3id.org/oc/corpus/', 'OpenCitations Corpus', 'Yes', NULL, '^https:\/\/identifiers\.org\/occ:[a-z][a-z]\/[0-9]+$', '^[a-z][a-z]/[0-9]+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R3C4E36F1', 'https://w3id.org/oc/meta/', 'OpenCitations is an independent not-for-profit infrastructure organization for open scholarship dedicated to the publication of open bibliographic and citation data by the use of Semantic Web (Linked Data) technologies. It is also engaged in advocacy for ', 'Yes', 'https://opencitations.net/meta/api/v1', '^https:\/\/identifiers\.org\/omid:[a-z][a-z]\/06[1-9]*0[1-9][0-9]*$', '^[a-z][a-z]/06[1-9]*0[1-9][0-9]*$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R274AD5FF', 'https://web.isan.org/public/en/search?domain=search&isan=$1', 'International Standard Audiovisual Number', 'Yes', 'http://sandbox.isan.org/api/v3/', '^https?:\/\/web\.isan\.org\/public\/en\/search\?domain=search&isan=(([A-F0-9]{4}\-){4}[A-Z0-9]\-([A-F0-9]{4}\-){2}[A-Z0-9])', '^([A-F0-9]{4}\-){4}[A-Z0-9]\-([A-F0-9]{4}\-){2}[A-Z0-9]', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RF19ABA30', 'https://www.catalogueoflife.org/data/taxon/', 'The Catalogue of Life website providing a view onto the latest release of the COL Checklist.', 'Yes', 'https://api.catalogueoflife.org/', '^https?:\/\/www\.catalogueoflife\.org\/data\/taxon\/([23456789BCDFGHJKLMNPQRSTVWXYZ]{1,6}) ', '^[23456789BCDFGHJKLMNPQRSTVWXYZ]{1,6}$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RE125C01D', 'https://www.chemspider.com/InChI/Resolve.aspx?InChIKey=', 'InChIKey through ChemSpider', 'Yes', NULL, '^https:\/\/www.chemspider.com\/InChI\/Resolve.aspx?InChIKey=[A-Z]{14}\-[A-Z]{10}(\-[A-Z])?$', '^[A-Z]{14}\-[A-Z]{10}(\-[A-Z])?', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RC4517C11', 'https://www.ebi.ac.uk/biosamples/', 'BioSamples Database at EBI', 'Yes', 'https://www.ebi.ac.uk/biosamples/', '^https:\/\/www\.ebi\.ac\.uk\/biosamples\/sample\/{$id}', '^SAM[NED](\w)?\d+$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RE8C7548A', 'https://www.geonames.org/', 'GeoNames ID', 'Yes', 'http://api.geonames.org/postalCodeSearch?', '^https?:\/\/(?:www\.|geotree\.)?geonames\.org\/([1-9][0-9]{0,8})', '([1-9][0-9]{0,8})', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RE7CA9ADB', 'https://www.getty.edu/research/tools/vocabularies/ulan/index.html', 'Union List of Artist Names ID', 'Yes', 'http://vocab.getty.edu/page/ulan/', NULL, '\d{9}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RA0476B5C', 'https://www.grid.ac/institutes/', 'GRID at Digital Science & Research Ltd.', 'Yes', NULL, '^https:\/\/identifiers\.org\/grid:grid\.[0-9]+\.[a-f0-9]{1,2}$', '^grid\.[0-9]+\.[a-f0-9]{1,2}$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R19236E0C', 'https://www.gs1.org/services/verified-by-gs1?gepir_redirect=1&utm_source=gepir_web&utm_medium=gepir_home&utm_campaign=vbg_replaces_gepir', 'EAN13 via gs1', 'Yes', 'https://ean-db.com/ , https://www.gs1.org/services', '^https://gepir.gs1.org/index.php/search-by-gtin?gtin=^\d{13}$', '^\d{13}$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R54DDFE0F', 'https://www.idref.fr/', 'IdRefID', 'Yes', 'https://www.idref.fr/Sru/Solr?', '^https?:\/\/(?:www\.)?idref\.fr\/(\d{8}[\dX]|)', '(\d{8}[\dX]|)', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R4B9D7776', 'https://www.igsn.org/resolve/', 'SESAR is a community platform that operates a sample registry for researchers, institutions, and sample facilities to openly share information about their samples. SESAR provides tools to upload sample metadata and register samples with IGSN as a globally', 'Yes', 'http://igsn.github.io/', '^https:\/\/www.igsn.org\/resolve\/IGSN:[A-Z0-9]{16}$', 'IGSN:[A-Z0-9]{16}$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R53136BAE', 'https://www.imdb.com/company/', 'Internet Movie Database Company Identifier', 'Yes', 'api-fulfill.dataexchange.us-east-1.amazonaws.com/v1', '^https?:\/\/www\.imdb\.com\/company\/co\d{7}', 'co\d{7}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RCF99DD66', 'https://www.imdb.com/name/', 'Internet Movie Database Name Identifier', 'Yes', 'api-fulfill.dataexchange.us-east-1.amazonaws.com/v1', '^https?:\/\/www\.imdb\.com\/name\/nm\d{7}', 'nm\d{7}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R2C585D33', 'https://www.imdb.com/title/', 'Internet Movie Database Title Identifier', 'Yes', 'api-fulfill.dataexchange.us-east-1.amazonaws.com/v1', '^https?:\/\/www\.imdb\.com\/title\/tt\d{7}\/', 'tt\d{7}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R3F468038', 'https://www.islrn.org/', 'International Standard Language Resource Number', 'Yes', 'https://www.islrn.org/', '^https?:\/\/www\.islrn\.org\/resources\/([0-9]{3}-[0-9]{3}-[0-9]{3}-[0-9]{3}-[0-9])$', '^[0-9]{3}-[0-9]{3}-[0-9]{3}-[0-9]{3}-[0-9]$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:P9A7C46D0', 'https://www.ismn-international.org/directory', 'International ISMN Agency Resolver', 'Yes', NULL, NULL, '^979-0-\d{4,9}-\d{1,5}-\d$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R3666E047', 'https://www.ncbi.nlm.nih.gov/bioproject/', 'BioProject Database Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/bioproject\/[0-9]+', '[0-9]+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RCB580056', 'https://www.ncbi.nlm.nih.gov/biosample/', 'BioSample at NCBI', 'Yes', 'eutils.ncbi.nlm.nih.gov', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/biosample\/SAM[NED](\w)?\d+$', '^SAM[NED](\w)?\d+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RCEFFFBBA', 'https://www.ncbi.nlm.nih.gov/datasets/genome/', 'NIH Genome Accession Number', 'Yes', 'https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/rest-api/#get-/genome/accession/-accessions-/download_summary', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/datasets\/genome\/(GCA|GCF)_\d{9}(\.\d+)?', '(GCA|GCF)_\d{9}(\.\d+)?', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R5B020C66', 'https://www.ncbi.nlm.nih.gov/dbvar/variants/nsv3874286/', 'Database of Genomic Structural Variation', 'Yes', 'https://clinicaltables.nlm.nih.gov/apidoc/dbvar/v3/doc.html', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/dbvar\/variants\/nsv\d+\', 'nsv\d+\', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R673F8F1B', 'https://www.ncbi.nlm.nih.gov/gene/10100523', 'NIH Gene ID Accession Number', 'Yes', 'https://clinicaltables.nlm.nih.gov/apidoc/ncbi_genes/v3/doc.html', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/gene\/\d+', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RDFC37F26', 'https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=', 'Geo DataSets Accession Number', 'Yes', 'https://www.ncbi.nlm.nih.gov/geo/info/geo_paccess.html', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/geo\/query\/acc\.cgi?acc=(GSE|GSM|GPL|GDS)\d{3,6}', '(GSE|GSM|GPL|GDS)\d{3,6}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R4F125F9F', 'https://www.ncbi.nlm.nih.gov/geoprofiles/86461725', 'GEO Profiles Accession Number', 'Yes', 'https://www.ncbi.nlm.nih.gov/geo/info/geo_paccess.html', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/geoprofiles\/\d+', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RC4A84871', 'https://www.ncbi.nlm.nih.gov/mesh/68057208', 'Medical Subject Headings Accession Number', 'Yes', 'https://id.nlm.nih.gov/mesh/swagger/swagger.json', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/mesh\/\d+', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R15C35878', 'https://www.ncbi.nlm.nih.gov/nlmcatalog', 'NCBI NLM Catalog Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/nlmcatalog\/\d+', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RE44E4DEB', 'https://www.ncbi.nlm.nih.gov/nuccore/', 'NCBI Nucleotide Database Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/nuccore\/\b([A-Z]{2}_[0-9]{6,})\b', '\b([A-Z]{2}_[0-9]{6,})\b', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R06525948', 'https://www.ncbi.nlm.nih.gov/pmc/', 'PubMed Central DB Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/pmc\/PMC\d+', 'PMC\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RBC19BCE8', 'https://www.ncbi.nlm.nih.gov/popset', 'NCBI PopSet ID Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/popset\/\d+', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R4E9828AD', 'https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=', 'The database of Genotypes and Phenotypes (dbGaP)', 'Yes', NULL, '^https?:\/\/www\.ncbi\.nlm\.nih\.gov\/projects\/gap\/cgi-bin\/study\.cgi\?study_id=(phs\d{6}\.v\d+\.\w\d+)$', '(phs\d{6}\.v\d+\.\w\d+)', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R28D87F1D', 'https://www.ncbi.nlm.nih.gov/protein/', 'NCBI Protein Database Accession Number', 'Yes', 'https://www.ebi.ac.uk/proteins/api/doc/', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/protein\/\b[A-Z]{3}[0-9]{5}\.[0-9]\b', '\b[A-Z]{3}[0-9]{5}\.[0-9]\b', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R1460583C', 'https://www.ncbi.nlm.nih.gov/proteinclusters/', 'NCBI Protein Cluster Database Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/proteinclusters\/\d+', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R50DBC771', 'https://www.ncbi.nlm.nih.gov/snp/', 'PubMed SNP DB Accession Number', 'Yes', 'https://clinicaltables.nlm.nih.gov/api/snps/v3/search?terms=', '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/snp\/rs\d+', 'rs\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R84DB34AC', 'https://www.ncbi.nlm.nih.gov/sra/', 'PubMed SRA DB Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/sra\/SR[ASED][0-9A-Z]+(\[[^\]]+\])?$', '^SR[ASED][0-9A-Z]+(\[[^\]]+\])?$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R2489E74F', 'https://www.ncbi.nlm.nih.gov/Structure/', 'NCBIs Structure Database Accession Number', 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R865711ED', 'https://www.ncbi.nlm.nih.gov/Structure/cdd/cddsrv.cgi?uid=394797', 'Position Specific Scoring Matrix', 'Yes', 'https://www.ncbi.nlm.nih.gov/Structure/bwrpsb/bwrpsb.cgi?', '^https?:\/\/www\.ncbi\.nlm\.nih\.gov\/Structure\/cdd\/cddsrv\.cgi\?uid=([a-zA-Z0-9]+)$', '^\d{6}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R2FD9E705', 'https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=', 'NCBIs Taxonomy Database Accession Number', 'Yes', NULL, '^https:\/\/www.ncbi.nlm.nih.gov\/Taxonomy\/Browser\/wwwtax\.cgi\?id=\d+$', '^\d+$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R735188BC', 'https://www.ncbi.nlm.nih.gov/toolkit/', 'NCBI C++ Toolkit Accession Number', 'Yes', NULL, '^https:\/\/www\.ncbi\.nlm\.nih\.gov\/toolkit\/\d+', '\d+', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R284D8E0C', 'https://www.persistent-identifier.nl/', NULL, 'Yes', 'http://www.persistent-identifier.nl/', '^https?:\/\/www\.persistent-identifier\.nl/(?i)(urn:nbn:nl.+)', '(?i)(urn:nbn:nl.+)', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R4DE67922', 'https://www.pidconsortium.net/', 'ePIC resolved at PID Consortium', 'Yes', 'https://doc.pidconsortium.eu/docs/ https://epic.grnet.gr/docs/', '^https:\/\/epic\.grnet\.gr\/handle\/21\.T12996\/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}', '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R7B15D54B', 'https://www.proquest.com/articlelinker.asp', 'OpenURL via UKOLN', 'N/A', 'https://www.oclc.org/research/activities/openurl.html', '^https?:\/\/www\.ukoln\.ac\.uk\/distributed-systems\/openurl\/\?sid=([^&]+)&aulast=([^&]+)&atitle=([^&]+)&title=([^&]+)&issn=([^&]+)&volume=([^&]+)&spage=([^&]+)&epage=([^&]+)&date=([^&]+)$', '^sid=([^&]+)&aulast=([^&]+)&atitle=([^&]+)&title=([^&]+)&issn=([^&]+)&volume=([^&]+)&spage=([^&]+)&epage=([^&]+)&date=([^&]+)$', 'N/A', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R64ABE777', 'https://www.protocols.io/protocols/', 'Research Resource Identifier via SciCrunch', 'Yes', NULL, 'https:\/\/www.protocols.io\/protocols\/^RIN:\d+$', '^RIN:\d+$', 'Yes', 'Yes', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RFB670458', 'https://www.re3data.org/repository/', 'Identifier for a data repository in the re3data registry', 'Yes', NULL, '^https?:\/\/www\.re3data\.org\/repository\/(r3d[1-9]\d{0,8})', '^r3d\d{9,9}$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R9B691867', 'https://www.scopus.com/authid/detail.uri?authorId=', 'ScopusAuthorID', 'Yes', 'https://api.elsevier.com/content/search/scopus', '^https?:\/\/(?:www\.)?scopus\.com\/authid\/detail\.ur[il]\?authorId=([1-9]\d{9,10})', '[1-9]\d{9,11}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R639F433B', 'https://www.suomi.fi/', NULL, 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R9F98C519', 'https://www.upcitemdb.com/upc/', 'Universal Product Code', 'Yes', 'https://api.upcitemdb.com/prod/trial/lookup?upc=', '^https:\/\/www.upcitemdb.com\/upc\/\d{12}$', '^\d{12}$', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R9D9F7435', 'https://www.webofscience.com/wos/author/record/', 'Researcher ID via Web of Science', 'Yes', 'https://api.clarivate.com/apis/wos-researcher', '^https:\/\/(?:www\.)?webofscience\.com\/wos\/author\/record\/[A-Z]{1,3}-\d{4}-(19|20)\d\d', '[A-Z]{1,3}-\d{4}-(19|20)\d\d', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RF735C567', 'https://www.webofscience.com/wos/woscc/full-record/WOS:', 'Web of Science ID', 'Yes', NULL, '^https?:\/\/cel\.webofknowledge\.com\/InboundService\.do\;jsessionid=[\dA-Z]+\?[\w=\-&]*UT=WOS:([A-Z\d]{15})', '[A-Z\d]{15}', 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R3CD417A6', 'https://www.wikidata.org/wiki/', 'Wikidata at Wikimedia Foundation', 'Yes', 'https://wikidata.org/w/rest.php/wikibase/v0', '^https?:\/\/(?:www\.)?wikidata/.org\/wiki\/(Q|P)\d+$', '^(Q|P)\d+$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:PB5C240AF', 'https://zbmath.org/ ', NULL, 'Yes', NULL, NULL, NULL, 'Yes', NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:RF02894C2', 'https://zbmath.org/?q=an:', NULL, 'Yes', NULL, '^https:\/\/zbmath.org\/?q=an:\d{8}$', '^\d{8}$', 'Yes', 'No', '2025-02-10 06:49:01+01', '0000-0002-0255-5101');
INSERT INTO k_Resolver(lodRES, labelResolver, descResolver, defaultValue, apiUrl, httpMethod, regexPattern, primaryResolver, curieFormat, lastTouch, populatedBy) VALUES ('pid_graph:R606E3A09', 'Nucleotide GI Number', 'NCBI Nucleotide Database Accession Number', NULL, NULL, NULL, NULL, NULL, NULL, '2025-02-10 06:49:01+01', '0000-0002-0255-5101');