-- ------------------------------------------------
-- Version: v1.2
--
-- Description: Migration that introduces the provider table
-- -------------------------------------------------

DROP TABLE k_Manager_Provider;
DROP TABLE k_Provider;
DROP TABLE k_Manager;

CREATE TABLE k_Provider (
    IDPRV integer,
    lodPRV character varying(255) NOT NULL,
    PRV character varying(255),
    labelProvider character varying(255),
    descProvider text,
    lodTPR character varying(255),
    lodPRV_V character varying(255),
    Country text,
    startDate timestamp with time zone,
    populatedBy character varying(255),
    lastTouch date,
    PRIMARY KEY (lodPRV)
);



INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6AA27949', NULL, 'RAID Australia', NULL, 'pid_graph:DB893DE8', NULL, 'AUS', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3C391CE0', NULL, 'Australian Research Data Commons (ARDC)', 'Sample holders and curators affiliated with Australian research organisations that do not offer their own IGSN minting service', 'pid_graph:DB893DE8', NULL, 'AUS', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F46811F9', NULL, 'Commonwealth Scientific and Industrial Research Organisation (CSIRO)', 'Organization facilities and staff', 'pid_graph:DB893DE8', NULL, 'AUS', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9CE13EF4', NULL, 'Geoscience Australia', 'Organization facilities and staff', 'pid_graph:DB893DE8', NULL, 'AUS', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5808D13E', NULL, 'AuScope', 'AuScope Sample Catalogue and IGSN Registration Service', 'pid_graph:DB893DE8', NULL, 'AUS', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C496EAD7', NULL, 'Austrian National Library', NULL, 'pid_graph:DB893DE8', NULL, 'AUT', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:650F2243', NULL, 'KBR (Royal Library of Belgium)', 'The Royal Library of Belgium is the national scientific library in Belgium. It collects all Belgian publications and preserves, manages and studies an extensive cultural and historical heritage. It provides the public with access to information, facilitates research and offers a broad cultural experience.', 'pid_graph:DB893DE8', NULL, 'BEL', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F6308707', NULL, 'Câmara Brasileira do Livro (CBL)', 'Brazilian Book Chamber (CBL) is a non-profit association, representing publishers, booksellers, distributors, and other professionals in the sector. CBL promotes access to books and the democratization of reading throughout the country, as well as promoting Brazilian literature in the international market.', 'pid_graph:DB893DE8', NULL, 'BRA', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0744D7A2', NULL, 'Bibliothèque et Archives nationales du Québec (BAnQ)', 'Bibliothèque et Archives nationales du Québec (BAnQ) collects, processes, preserves and promotes the Quebec documentary heritage and a vast collection of documents in all fields. It provides the services of a major public library to the entire population of Quebec.', 'pid_graph:DB893DE8', NULL, 'CAN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0320244D', NULL, 'China Knowledge Centre for Engineering Sciences and Technology (CKCEST)', 'The China Knowledge Centre for Engineering Sciences and Technology (CKCEST) utilises the digital resources of relevant universities, research institutes, enterprises and other entities across the country to establish a knowledge centre featuring rich resources with strong practicality and a broad scope of application. ', 'pid_graph:DB893DE8', NULL, 'CHN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C794C66B', NULL, 'Chinese DOI', 'Chinese DOI is a DOI registration service jointly run by ISTIC & Wanfang Data, and it was the first DOI RA in China and Asia. It mainly provides DOI registration, resolution and other value-added services to Chinese publishers, research institutions, service providers and researchers for research content such as academic journals, scientific data, dissertations, books, conference proceedings, preprints, etc. ISTIC (Institute of Science and Technology Information of China) is a national public beneficial research institute under the Ministry of Science and Technology of China, and Wanfang Data (Wanfang Data Co., Ltd. & Wanfang Data CORP. (INTL) LTD) is the leading science and technology information service provider in China.', 'pid_graph:DB893DE8', NULL, 'CHN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F29743FC', NULL, 'CNIC', 'The Computer Network Information Center (CNIC) of the Chinese Academy of Sciences (CAS) provides research network, data, computing, resource planning services to the scientific communities, and Internet-based science outreach service to the general public.', 'pid_graph:DB893DE8', NULL, 'CHN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FCECC2D2', NULL, 'CNKI', 'China National Knowledge Infrastructure (CNKI) manages China-based information resources, including Chinese politics, economics, humanities, social science, science, and technology. CNKI publishes databases containing e-journals, newspapers, dissertations, proceedings, yearbooks, references', 'pid_graph:DB893DE8', NULL, 'CHN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AAB4FC28', NULL, 'National and University Library in Zagreb', NULL, 'pid_graph:DB893DE8', NULL, 'HRV', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:353B65A6', NULL, 'National Library of the Czech Republic', NULL, 'pid_graph:DB893DE8', NULL, 'CZE', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D4CCA3D7', NULL, 'CSC', 'IT Center for Science (CSC) provide tools for scientific computing and data management in Finland. They connect Finnish higher education institutions, researchers, and students to each other and to the whole world. ', 'pid_graph:DB893DE8', NULL, 'FIN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B87EEF45', NULL, 'Federation of Finnish Learned Societies (TSV) in Finland', NULL, 'pid_graph:DB893DE8', NULL, 'FIN', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B393463B', NULL, 'National Library of Finland', 'The National Library of Finland is a cultural heritage organisation that is open to all and provides nationwide services to citizens, scientific communities and other societal operators. It secures the availability of cultural heritage published in Finland or relating to Finland as well as transmits and produces information content for research, studies, citizens and the society.', 'pid_graph:DB893DE8', NULL, 'FIN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C3582F72', NULL, 'Statistics Finland', NULL, 'pid_graph:DB893DE8', NULL, 'FIN', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AC92BDCD', NULL, 'Virta Ltd.', NULL, 'pid_graph:DB893DE8', NULL, 'FIN', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C3F73B86', NULL, 'ABES', 'Agence Bibliographique de l''Enseignement Supérieur (ABES)', 'pid_graph:DB893DE8', NULL, 'FRA', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B932C3AD', NULL, 'Bibliothèque nationale de France (BnF)', 'The ISNI Registration Agency at the BnF undertakes to identify in the most comprehensive way possible the public identities of persons and communities contributing to the national documentary heritage. It shall apply to the request for the allocation of ISNI to its authority data (Person and Community). It shall ensure the dissemination of these ISNI identifiers in MARC and in the formats of the semantic web.', 'pid_graph:DB893DE8', NULL, 'FRA', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1DC03610', NULL, 'HAL (Hyper Articles en Ligne)', NULL, 'pid_graph:DB893DE8', NULL, 'FRA', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F9C2FE9F', NULL, 'Centre national de la recherche scientifique (CNRS)', 'Researchers funded by CNRS.', 'pid_graph:DB893DE8', NULL, 'FRA', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9AE6AE97', NULL, 'Institut Français de Recherche pour l’Exploitation de la Mer (IFREMER)', 'Organization facilities and staff', 'pid_graph:DB893DE8', NULL, 'FRA', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:75B1FCDA', NULL, 'International ISBN Agency', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D1DB7F9F', NULL, 'DKRZ', 'The German Climate Computing Center (Deutsches Klimarechenzentrum, DKRZ) is a central service center for German climate and earth system research. Its high performance computers, data storage and services form the central research infrastructure for simulation-based climate science in Germany. ', 'pid_graph:DB893DE8', NULL, 'DEU', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AF6411A6', NULL, 'German Research Centre for Geosciences (GFZ)', 'GFZ Data Services at the Helmholtz Centre offers an IGSN Registration Service. ', 'pid_graph:DB893DE8', NULL, 'DEU', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8BA669F9', NULL, 'GEOMAR Helmholtz-Zentrum für Ozeanforschung Kiel/ Kiel University', 'The IGSN service is available to all employees and institutions of Kiel University.', 'pid_graph:DB893DE8', NULL, 'DEU', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E956333B', NULL, 'German National Library (DNB)', NULL, 'pid_graph:DB893DE8', NULL, 'DEU', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:27F7E471', NULL, 'German Research Foundation (DFG)', NULL, 'pid_graph:DB893DE8', NULL, 'DEU', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:65A98C52', NULL, 'National Széchényi Library', NULL, 'pid_graph:DB893DE8', NULL, 'HUN', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E680F29D', NULL, 'Library of Trinity College Dublin, University of Dublin', 'The Library of Trinity College Dublin supports the learning and research needs across all disciplines of the college. It is a major research library providing services to a wide range of external users and institutions. It contributes to the development of creative initiatives in information provision and its exhibitions of manuscripts and other treasures attracts hundreds of thousands of visitors to visit the Old Library each year.', 'pid_graph:DB893DE8', NULL, 'IRE', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C6D924E8', NULL, 'Italian Central Institute for Cataloguing and Documentation (ICCU)', NULL, 'pid_graph:DB893DE8', NULL, 'ITA', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B09F8820', NULL, 'JaLC', 'The Japan Link Center (JaLC) provides public information services to promote science and technology in Japan. Scientific and academic metadata and content from holders nationwide, including national institutes, universities, government organisations, and commercial publishers. Operated by Japan Science and Technology Agency, National Institute of Material Science, National Institute of Informatics, and National Diet Library. Collaboration with Crossref and DataCite for global distribution.', 'pid_graph:DB893DE8', NULL, 'JPN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:33A4BB68', NULL, 'KISTI', 'The Korean DOI Center is operated by the Korea Institute of Science and Technology Information (KISTI). They collect bibliographic information of Korean science and technology information and data, including journal articles, proceedings, official Government documents, Korean patent information, R&D Reports and traditional Korean knowledge. In addition, the Korean DOI Center promotes the use of the collected information and data in Korea and improve access to Korean research achievements.', 'pid_graph:DB893DE8', NULL, 'KOR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:32BB916F', NULL, 'National Assembly Library of Korea', 'The National Assembly Library of Korea is the largest humanities and social sciences library in the country, and functions as both a parliamentary and public library. It was established to collect a wealth of information from around the world and deliver it to both the members of the National Assembly and the general public.', 'pid_graph:DB893DE8', NULL, 'KOR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8C3ABE90', NULL, 'National Library of Korea', 'The National Library of Korea is a dynamic hub for knowledge, research, and lifelong learning. It maintains an online catalogue, digital archives, and various educational and cultural programs.', 'pid_graph:DB893DE8', NULL, 'KOR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AF8DFCEF', NULL, 'National Research Foundation of Korea (NRF)', NULL, 'pid_graph:DB893DE8', NULL, 'KOR', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D2444AE0', NULL, 'Korea Institute of Geoscience and Mineral Resources (KIGAM)', 'Korea’s geoscience research and academic sectors.', 'pid_graph:DB893DE8', NULL, 'KOR', NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D2D0AB0F', NULL, 'Bibliothèque nationale de Luxembourg', 'The Bibliothéque Nationale de Luxembourg collects, catalogues and preserves all analogue and digital publications published in Luxembourg and any works published abroad that relate to the Grand Duchy. It is the country’s leading academic, research and cultural heritage library. In order to meet the requirements of its users, about three-quarters of its printed collections come from other countries and they cover different fields of knowledge.', 'pid_graph:DB893DE8', NULL, 'LUX', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DA6693BF', NULL, 'Koninklijke Bibliotheek', 'The KB is the National Library of the Netherlands. Its aim is to collect as many publications as possible written in or about the Netherlands. The library is comprised of a repository in The Hague and an extensive digital collection. It also hosts services such as the Online Library, Delpher and DBNL (the Digital Library for Dutch Literature).', 'pid_graph:DB893DE8', NULL, 'NLD', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9F6AC0F7', NULL, 'Royal Library of the Netherlands', NULL, 'pid_graph:DB893DE8', NULL, 'NLD', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:012DA850', NULL, 'SURF', 'SURF is the collaborative ICT organisation for higher education and research in the Netherlands', 'pid_graph:DB893DE8', NULL, 'NLD', NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B7D3F8B5', NULL, 'New Zealand Companies Office', NULL, 'pid_graph:DB893DE8', NULL, 'NZL', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:14EA6178', NULL, 'National Library of Norway', 'The National Library of Norway serves as Norway’s national memory. The collection is home to Norwegian knowledge and heritage with a physical location in Solli and an online repository. The services of the library are free and open to the public. ', 'pid_graph:DB893DE8', NULL, 'NOR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:79DB44B8', NULL, 'National Library of Poland', 'The National Library of Poland acts as the central library of the country and is one of the most important cultural institutions in Poland. Its mission is to protect national heritage preserved in the form of handwritten, printed, electronic, recorded sound and audiovisual documents. The primary task of the National Library of Poland is to acquire, store and permanently archive the intellectual output of Poles, including the works of citizens living on Polish soil, the most important foreign works, and publications related to Poland and published abroad.', 'pid_graph:DB893DE8', NULL, 'POL', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5F4069FD', NULL, 'National Awareness Centre (Slovakia)', NULL, 'pid_graph:DB893DE8', NULL, 'SVK', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C7531219', NULL, 'National and University Library of Slovenia', NULL, 'pid_graph:DB893DE8', NULL, 'SVN', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9DBAE1BE', NULL, 'University of Ljubljana, Faculty of Social Sciences', NULL, 'pid_graph:DB893DE8', NULL, 'SVN', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A1C6B677', NULL, 'Biblioteca nacional de España', 'The Biblioteca Nacional de España (National Library of Spain) is a major public library located in Madrid, on the Paseo de Recoletos.', 'pid_graph:DB893DE8', NULL, 'ESP', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C688E761', NULL, 'National Library of Sweden', NULL, 'pid_graph:DB893DE8', NULL, 'SWE', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:138F5B2F', NULL, 'International ISTC Agency', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B5D02F72', NULL, 'CSCS', 'The Swiss National Supercomputing Centre (CSCS) develops and operates cutting-edge high-performance computing systems as an essential service facility for Swiss researchers.', 'pid_graph:DB893DE8', NULL, 'CHE', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7AA2E7F6', NULL, 'Swiss National Library', NULL, 'pid_graph:DB893DE8', NULL, 'CHE', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F23932AE', NULL, 'Airiti', 'Airiti DOI is a Taiwan-based registration agency operated by Airiti, which is a service provider deeply involved in the scholarly community of the Chinese-speaking area. They manage applications to Chinese and English materials, incorporating the DOI into the digital publishing process, saving time and money for their members and partners. In addition to DOI registration services, Airiti DOI also develops and provides value-added services that support academic publishing, such as DOI Resolution, DOI Data Finder (search DOI names and metadata), DOI resolution data download, and Cited by Link.', 'pid_graph:DB893DE8', NULL, 'TWN', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:723A3E8C', NULL, 'Republic of Türkiye Ministry of Culture and Tourism', 'The Ministry of Culture and Tourism is a government ministry of the Republic of Turkey, responsible for culture and tourism affairs in Turkey.', 'pid_graph:DB893DE8', NULL, 'TUR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:66DB4934', NULL, 'Bodleian Library, University of Oxford', 'The Bodleian Libraries is the library service supporting the University of Oxford. The mission of the Bodleian Libraries is to provide an excellent service to support the learning, teaching and research objectives of the University of Oxford; and to develop and maintain access to Oxford''s unique collections for the benefit of scholarship and society.', 'pid_graph:DB893DE8', NULL, 'GBR', NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:692E6BE7', NULL, 'British Library', 'The British Library is the national library of the UK. The library is free to use and open to everyone. It works with partners and other libraries to make its collection as accessible as possible.', 'pid_graph:DB893DE8', NULL, 'GBR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8C8A02AB', NULL, 'Cambridge University Library', 'The library of Cambridge University preserves the worlds knowledge in physical and digital form. As one of the UK and Ireland’s six Legal Deposit Libraries, Cambridge University Library has been entitled to request every publication in both the UK and Ireland since 1710. In addition to its physical collections, the library allows access to tens of millions of electronic articles, books, journals, scores and other e-resources.', 'pid_graph:DB893DE8', NULL, 'GBR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6ADA1073', NULL, 'National Library of Scotland', 'The National Library of Scotland is answerable to the Scottish Parliament and funded by the Scottish Government. It remains one of only six legal deposit libraries in the United Kingdom and Ireland and is governed by a board of management. Its mission is to enhance Scotland''s international reputation by making a significant contribution to global knowledge and the memory of the world.', 'pid_graph:DB893DE8', NULL, 'GBR', NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:591D90E5', NULL, 'National Library of Wales', 'The National Library of Wales (NLW) is a legal deposit library holding a right to a copy of every publication printed in Britain and Ireland. The library is physically located in Abserystwyth but some of its collection has been digitized and can be viewed online.   ', 'pid_graph:DB893DE8', NULL, 'GBR', NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4CA9BB01', NULL, 'UK National Archives', NULL, 'pid_graph:DB893DE8', NULL, 'GBR', NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A7074BF7', NULL, 'AETIS', 'AETIS is a digital platform designed to support the growth and development of businesses and individuals working in creative industries, such as music, art, design, film, and advertising, by providing them with online tools, and resources, to protect their Intellectual Property Rights almost instantly. AETIS brings together innovative technology and IP protection experts worldwide to lay the foundation for the global expansion of creative industries, culture and innovative businesses.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4491BAB1', NULL, 'ARK Alliance', 'The ARK Alliance is an open global community supporting the ARK infrastructure on behalf of research and scholarship. Archival Resource Keys (ARKs) serve as persistent identifiers, or stable, trusted references for information objects. Among other things, they aim to be web addresses (URLs) that don’t return 404 Page Not Found errors.', 'pid_graph:FBFDB448', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:78C5DD5E', NULL, 'arXiv.org', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:24B83E30', NULL, 'B2INST', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:508240F7', NULL, 'Bibliographic Data Services', 'Bibliographic Data Services (BDS) aggregates, curates and delivers metadata relating to print and e-books, audiobooks, film, music and video games. BDS also specialises in the design, build, hosting and maintenance of websites for the book trade and home entertainment industry.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:530D0168', NULL, 'Bitbucket', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:01F7DFBA', NULL, 'BSI Identify', 'BSI Identify is a service operated by BSI to provide unambiguous identification for products and the long-term persistent storage of associated product information that can be accessed using a digital ID called a UPIN (Unique Persistent Identification Number). The service provides a consistent approach to identification of construction products that supports the industry as it continues to digitize and addresses critical safety issues.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C9E0E092', NULL, 'BTLF (Société de gestion de la Banque de Titres de Langue Française)', 'The BLTF management company contributes to improving the marketing of French-language publishing products in Canada and Quebec; fostering the promotion and encouraging the marketing of Canadian and Quebec French-language publishing products abroad; encouraging and fostering communication and collaboration between publishers, booksellers, distributors, librarians and other participants in the book industry.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:33C4D427', NULL, 'Casalini Libri', 'Casalini Libri supplies publications from across Southern Europe to libraries and institutions worldwide. It provides services for libraries and publishers. Its Torrossa platforms aims to simplify acquisitions, licensing, and integration with the library catalogue.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:71572A11', NULL, 'Catalogue of Life (COL)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:158F1A3C', NULL, 'CLARIN', 'The Common Language Resources and Technology Infrastructure (CLARIN) is a digital infrastructure which provides easy and sustainable access to a broad range of language data and tools to support research in the humanities and social sciences, and beyond. CLARIN provides access to multimodal digital language data (text, audio, video) and advanced tools with which to explore, analyse or combine these datasets.', 'pid_graph:FBFDB448', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:ACA4FB20', NULL, 'Clarivate Analytics', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0F0DCC2E', NULL, 'International Organisation for Standardization (ISO) and ITU-T', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:44F64F9F', NULL, 'Consolidated Independent (CI)', 'Consolidated Independent is a London based company connecting labels and artists with the opportunities and services of the global digital market. CI’s position as part of the state51 Music Group provides access to their supply side technology platform. ', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:78CB2A61', NULL, 'Corporation for National Research Initiatives (CNRI)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D51999D1', NULL, 'CrossRef', 'Crossref is a global community infrastructure making all kinds of research objects easy to find, assess, and reuse through a number of services critical to research communications. Their 18,000+ members come from 148 countries and their ~140 million DOI records contribute to the collective vision of a rich and reusable open network of relationships connecting research organisations, people, things, and actions; a scholarly record that the global community can build on forever, for the benefit of society.', 'pid_graph:FBFDB448', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:258448F0', NULL, 'DataCite', 'DataCite is a global non-profit organisation that provides DOIs for research data and all other research outputs. By assigning DataCite DOIs, research outputs become discoverable and associated metadata is made available to the community. DataCite develops additional services to make it easy to connect and share research outputs with the broader research ecosystem and to assess the use of outputs within that ecosystem. All organisations within the research community can join DataCite to start registering DOIs.', 'pid_graph:FBFDB448', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:ED720170', NULL, 'Decentralised', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4F922FE1', NULL, 'Deep Carbon Observatory', 'DCO-ID is the DCO implementation of the Global Handle System (superset of Digital Object Identifier).', 'pid_graph:F1662576', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5FB541DE', NULL, 'Deep Carbon Observatory (DCO) (defunct)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:23DB5BB4', NULL, 'EIDR', 'The Entertainment Identifier Registry (EIDR) provides identification services for Content Identifers and Video Service Identifers. Content IDs are a registry of movies, television shows, radio programs, podcasts, and other audio/video assets of commercial, cultural, historic, or scientific interest. Video Service IDs are a registry of content delivery services including terrestrial broadcast channels, satellite delivery channels, cable television networks, Internet streaming services, etc. EIDR IDs are commonly used for process automation, linked data, engineering standards, academic citation, universal search, and so forth.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:393211A0', NULL, 'Entertainment Identifier Registry Association (EIDR)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6FC02CC0', NULL, 'EU-OP', 'The Publications Office of the European Union is the official provider of publishing services to all EU institutions, bodies and agencies. Its mission is to support EU policies as a centre of excellence for information, data and knowledge management, and to ensure that this broad range of information is available to the public as accessible and reusable data to facilitate transparency, economic activity and the diffusion of knowledge.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:ECDBAB97', NULL, 'European Commission', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:71E5F007', NULL, 'GeoNames.org', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D43A6D07', NULL, 'Getty Research Institute', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2DEE4AE8', NULL, 'GitHub, Inc.', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F0037977', NULL, 'GitLab Inc.', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DB82ABA9', NULL, 'Global Research Identifier Database (GRID)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:88325889', NULL, 'GRNET', 'Greek Research and Technology Network (GRNET) provides networking, cloud computing, HPC, data management services and e-Infrastructures and services to academic and research institutions, to educational bodies at all levels, and to all agencies of the public sector in Greece.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2D819813', NULL, 'GS1', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1EE367AE', NULL, 'GWDG', 'Gesellschaft für wissenschaftliche Datenverarbeitung Göttingen (GWDG) is a service organization which works in conjunction with the University of Göttingen and the Max Planck Society as a data and IT service center. It also carries out independent research in the field of computer science and provides support in preparing future professionals for a career in information technology.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8B3C5C36', NULL, 'HAND', 'Human & Digital (HAND) is a Talent Identifier built for the business requirements of Hollywood & sports. By identifying Legal Entity Humans, Licensed Virtual Humans, and Fictional Characters, HAND provides the interoperable Talent ID the industry needs for historical, present, and future uses.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DCD3FC34', NULL, 'IANA', 'The Internet Assigned Numbers Authority (IANA) is a standards organisation that oversees global IP address allocation, autonomous system number allocation, root zone management in the Domain Name System (DNS), media types, and other Internet Protocol–related symbols and Internet numbers.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:65D51A09', NULL, 'ICCU - Istituto Centrale per il Catalogo Unico della Biblioteche Italiane per le informazioni bibliografiche', 'The Central Institute for the Union Catalogue of Italian Libraries and Bibliographic Information (Istituto Centrale per il Catalogo Unico delle biblioteche italiane e per le informazioni bibliografiche - ICCU) was created in 1951 with the task of cataloguing the entire national bibliographic heritage. The Institute cooperates with the Italian libraries carrying out coordination functions and promoting cataloguing projects which make the use of information technology.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:CEA1CCB4', NULL, 'Identification Agency (IDA)', 'The Identification Agency (IDA) is a Russian organization tasked with registering and maintaining International Standard Name Identifiers.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6498B100', NULL, 'IGSN e.v.', 'The IGSN ID is a globally unique, persistent, domain-agnostic identifier for material samples. Samples can be any material from anywhere in the universe, not only from Earth. Even though IGSN had its roots in geosciences, it really is now for all sample types from all disciplines.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:37CEA8A5', NULL, 'IMDb', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:34072556', NULL, 'International Article Number (EAN)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:56BF54AA', NULL, 'International Federation of the Phonographic Industry (IFPI)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D25DE680', NULL, 'International Standard Language Resource Number Agency', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5097CE38', NULL, 'International Union of Pure and Applied Chemistry (IUPAC)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0CDD8999', NULL, 'Internet Archive', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:25BED641', NULL, 'ISAN International Agency', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B63833FF', NULL, 'ISMN Agency', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1B133F69', NULL, 'ISSN International Centre', NULL, 'pid_graph:FBFDB448', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:10A7646D', NULL, 'Library of Congress', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A19A5A5C', NULL, 'mEDRA', 'The multilingual European DOI Registration Agency (mEDRA) is a persistent citation system for Internet documents. Relation tracking between intellectual property entities. Certification of voluntary deposit including time stamping and digital signatures.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0959C132', NULL, 'Muso.AI', 'Muso.AI is a universal credit database designed to keep up with the digitization of music. Muso.AI is merging and cleaning up the music industry’s metadata and connecting creators with master rights holders to validate credits.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B92A63E8', NULL, 'MVB', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5742B6B8', NULL, 'NASA Astrophysics Data System (ADS)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F1F5DC6A', NULL, 'National Center for Biotechnology Information (NCBI)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E16BBCB2', NULL, 'National Information Standards Organization (NISO)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:99C92854', NULL, 'OASIS consortium', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7F247AB9', NULL, 'OASIS XRI Technical Committee', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3212F319', NULL, 'OCLC (Online Computer Library Center)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:980D999B', NULL, 'OpenCitations', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:80EA8CF5', NULL, 'ORCID', 'ORCID, which stands for Open Researcher and Contributor ID, is a global, not-for-profit organisation sustained by fees from our member organisations. ', 'pid_graph:FBFDB448', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:59E406A0', NULL, 'Orfium', 'Orfium uses machine learning technology to help creators, rights holders, and media companies track, report, and monetize usage of their music.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3D9AADCF', NULL, 'Program for Cooperative Cataloging', 'The Program for Cooperative Cataloging (PCC) is an international cooperative effort aimed at expanding access to library collections by providing useful, timely, and cost-effective cataloging that meets mutually-accepted standards of libraries around the world.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F38633A8', NULL, 'protocols.io', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0CC2415E', NULL, 'Quansic', 'Quansic maintains the largest artist graph database with over 2.5 million ISNIs and 180 million asset identifiers.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FB50A534', NULL, 'RAISE.eu', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, NULL, NULL);
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BF77595D', NULL, 'Relevant government agency in each country', NULL, 'pid_graph:DB893DE8', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:34E1F831', NULL, 'Resource Identification Initiative and Cellosaurus', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:99643B8E', NULL, 'Ringgold', 'Ringgold Identify Database is a curated database of the organizations that fund, create, and use scholarly research. Ringgold Identify Database helps stakeholders improve data quality, drive strategic decision-making, and support data interoperability.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F1F3CA08', NULL, 'Ringgold, Inc.', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8217B24E', NULL, 'RoR', 'The Research organisation Registry (ROR) is a global, community-led registry of open persistent identifiers for research organisations. ', 'pid_graph:F1662576', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4CF33A60', NULL, 'Rovix Inc.', 'The ISRC Team has been authorized by the Recording Industry Association of America (RIAA), as the US ISRC Agency, in compliance with the rules set forth by IFPI to issue ISRC Codes to our clients worldwide.', 'pid_graph:F1662576', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:42A731CC', NULL, 'SciCrunch/ Resource Identification Initiative', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2253F9A1', NULL, 'Scopus', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:20ADCB86', NULL, 'SND', 'The Swedish National Data Service (SND) is one of several national entities implementing the so-called Data Act, which is part of the European Union’s transition to a new system of open science. SND has a mission to create opportunities for researchers to describe, share, and reuse research data. They do this by supporting Swedish higher education institutions and other research organizations in establishing and operating local research data support functions (Data Access Units, DAU).', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:766E2022', NULL, 'Software Heritage', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9032CB3E', NULL, 'Sound Credit / Soundways', 'Sound Credit is a music credits platform with computer software applications for Windows, macOS, iOS, and Android. Sound Credit is used in the music industry through multimodal interaction, with a free user profile option including identifier code generation, data entry and editing software developed for information quality (IQ).', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7475B7DC', NULL, 'SoundExchange Inc.', 'SoundExchange is designated by the U.S. government to administer the Section 114 sound recording license. It collects and distributes digital performance royalties on behalf of 700,000 creators.Using proprietary technology that turns data into revenue SoundExchange has paid more than $11 billion in distributions to date. ', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4301C3C3', NULL, 'SPARWK', 'SPARWK helps creatives to expand their creative output, reach, network – administer their data, rights, career, and maximize their financial outcomes.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5F4F4BD6', NULL, 'Switchchord', 'Switchchord is a collective of musicians, lawyers, accountants, technologists, and songwriters dedicated to solving the hardest problems in the music industry. They create split sheets which help protect creatives’ work and income. They also provide metadata insights for publishers.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9E3A0D4D', NULL, 'Takwene', 'Takwene is a full-service interactive agency that helps clients succeed online by creating award-winning digital solutions. They provide advise on audience growth and tools to protect against copyright infringement and facilitate commerce.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8A00FB1C', NULL, 'TIDAL', 'TIDAL is a global music streaming platform. ', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6576BB21', NULL, 'Various (see details)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:84FC6E72', NULL, 'w3id.org', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B0767447', NULL, 'Warner Music Group (WMG)', 'Warner Music Group Corp., commonly abbreviated as WMG, is an American multinational entertainment and record label conglomerate headquartered in New York City. It is one of the big three recording companies and the third-largest in the global music industry, after Universal Music Group and Sony Music Entertainment', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:467FE089', NULL, 'Wikimedia Foundation', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FA845BA9', NULL, 'Wiseband', 'Wiseband is a music distributor distributing music online to all streaming services and download platforms.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C6B30B7D', NULL, 'World Health Organization (WHO)', NULL, 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2025-01-19');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4286C744', NULL, 'YouTube', 'YouTube is a global online video sharing platform owned by Google.', 'pid_graph:F1662576', NULL, NULL, NULL, '0009-0006-1756-5317', '2024-08-20');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C3FFCEE6', NULL, 'LithoDAT', 'Lithodat Pty Ltd offers IGSN registration and DOI registration. Lithodat can mint IGSNs for any sample or analysis, creating a Digital Twin and establishing a long-lasting reference with a public landing page for each IGSN.', 'pid_graph:F1662576', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2349E97E', NULL, 'MARUM Center for Marine Environmental Studies at University of Bremen', 'Organization facilities and staff', 'pid_graph:F1662576', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-18');
INSERT INTO k_Provider (IDPRV, lodPRV, PRV, labelProvider, descProvider, lodTPR, lodPRV_V, Country, StartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:55A906F6', NULL, 'System for Earth Sample Registration (SESAR) at Lamont-Doherty Earth Observatory, Columbia University', 'Registration by the general public supported; funded by the US National Science Foundation (NSF). SESAR is a community platform that helps make samples more discoverable, accessible, and reusable, and connects samples with the knowledge ecosystem derived from them.', 'pid_graph:F1662576', NULL, NULL, NULL, '0000-0002-0255-5101', '2024-08-18');
