-- ------------------------------------------------
-- Version: v1.26
--
-- Description: Migration that introduces the authority table
-- -------------------------------------------------

CREATE TABLE k_Authority (
    IDAUT integer,
    lodAUT character varying(255) NOT NULL,
    AUT character varying(255),
    labelAuthority character varying(255),
    descAuthority text,
    lodAUT_V character varying(255),
    populatedBy character varying(255),
    lastTouch character varying(255),
    PRIMARY KEY (lodAUT)
);

INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:00C7B7CF', 'ISBN', 'International ISBN Agency', 'Hosted by International ISBN Agency', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:00F7B08C', 'OCLC', 'OCLC (Online Computer Library Center)', 'Hosted by OCLC (Online Computer Library Center)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0217054B', 'National or Regional Tax Authorities', 'National or Regional Tax Authorities', 'National or Regional Tax Authorities', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0F69BD28', 'GitHub, Inc.', 'GitHub, Inc.', 'Hosted by GitHub, Inc. (a subsidiary of Microsoft)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1127BDAC', 'IMDb', 'IMDb', 'Hosted by IMDb (owned by Amazon)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:14F8124F', 'National Research Foundation of Korea (NRF)', 'National Research Foundation of Korea (NRF)', 'Hosted by National Research Foundation of Korea (NRF)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1924AC8D', 'National Széchényi Library', 'National Széchényi Library', 'Hosted by National Széchényi Library', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1987D400', 'UK National Archives', 'UK National Archives', 'Hosted by UK National Archives', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1A761A81', 'ICANN', 'Internet Corporation for Assigned Names and Numbers (ICANN)', 'Hosted by Internet Corporation for Assigned Names and Numbers (ICANN)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1B3CB788', 'Software Heritage', 'Software Heritage', 'Hosted by Software Heritage', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2460D453', 'GeoNames.org', 'GeoNames.org', 'Hosted by GeoNames.org', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:24A0ABCA', 'Scopus', 'Scopus', 'Hosted by Scopus', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:26F9E00B', 'Finnish Ministry of Education and Culture', 'Finnish Ministry of Education and Culture', 'Hosted by Finnish Ministry of Education and Culture', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2A9683BC', 'Royal Library of the Netherlands', 'Royal Library of the Netherlands', 'Hosted by Royal Library of the Netherlands', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2AE2D8F5', 'CCSD', 'Centre for Direct Scientific Communication (CCSD)', 'Hosted by CNRS (Centre National de la Recherche Scientifique)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2F1EAEDE', 'National Library of Korea', 'National Library of Korea', 'Hosted by National Library of Korea', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:35AAC5DE', 'National and University Library in Zagreb', 'National and University Library in Zagreb', 'Hosted by National and University Library in Zagreb', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3B3429F2', 'National Library of Norway', 'National Library of Norway', 'Hosted by National Library of Norway', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3B79C180', 'National Library of Sweden', 'National Library of Sweden', 'Hosted by National Library of Sweden', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:475996F0', 'WHO', 'World Health Organization (WHO)', 'Hosted by World Health Organization (WHO)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:47FE53B8', 'Bitbucket', 'Bitbucket', 'Hosted by Atlassian', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4E53874F', 'Not Applicable', 'Not Applicable', 'No Authority is applicable for this PID', NULL, NULL, '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4FF567CB', 'ICCU', 'Italian Central Institute for Cataloguing and Documentation (ICCU)', 'Hosted by Italian Central Institute for Cataloguing and Documentation (ICCU)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4FFDCD93', 'CLS', 'Committee for Library Standards', 'The Committee for Library Standards is the governing body of the GND-Kooperative. It is supported in its work by the GND Committee.', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:54DD9E76', 'OpenCitations', 'OpenCitations', 'Hosted by OpenCitations', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6004A7A9', 'OASIS XRI', 'OASIS XRI Technical Committee', 'Hosted by OASIS XRI Technical Committee', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:60449D57', 'Bitzi', 'Bitzi', 'Hosted by Bitzi', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:61D1C2B9', 'National and University Library of Slovenia', 'National and University Library of Slovenia', 'Hosted by National and University Library of Slovenia', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:693380F3', 'Publication Forum (Julkaisufoorumi)', 'Publication Forum (Julkaisufoorumi)', 'Hosted by Publication Forum (Julkaisufoorumi)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:69ADB8B5', 'Clarivate Analytics', 'Clarivate Analytics', 'Hosted by Elsevier', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7553F2EC', 'GitLab Inc.', 'GitLab Inc.', 'Hosted by GitLab Inc.', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7962C2F0', 'ISTC', 'International ISTC Agency', 'Hosted by International ISTC Agency', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7A447448', 'LoC', 'Library of Congress', 'Hosted by Library of Congress', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7D95C861', 'National Library of Finland', 'National Library of Finland', 'Hosted by National Library of Finland', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7E3E41A8', 'Catalogue of Life Secretariat', 'Catalogue of Life Secretariat', 'Hosted by GBIF', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7F908AED', 'DONA', 'DONA', 'Hosted by DONA', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:828D543E', 'ISLRNA', 'International Standard Language Resource Number Agency', 'Hosted by International Standard Language Resource Number Agency', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:82FB796D', 'OASIS', 'OASIS consortium', 'Hosted by OASIS consortium', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:88EECD30', 'National Library of the Czech Republic', 'National Library of the Czech Republic', 'Hosted by National Library of the Czech Republic', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8B15822A', 'W3C DID Working Group', 'W3C DID Working Group', 'Hosted by W3C DID Working Group', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8C88F9D3', 'National Research Foundation of Korea (NRF)', 'National Research Foundation of Korea (NRF)', 'Hosted by National Research Foundation of Korea (NRF)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8D3C34F3', 'University of Ljubljana, Faculty of Social Sciences', 'University of Ljubljana, Faculty of Social Sciences', 'Hosted by University of Ljubljana, Faculty of Social Sciences', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:981884A3', 'W3C', 'World Wide Web Consortium (W3C)', 'Hosted by World Wide Web Consortium (W3C)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9B5EBC6A', 'ISMN', 'ISMN Agency', 'Hosted by ISMN Agency', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A48238F2', 'Decentralised', 'Decentralised', 'Decentralised Authority', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A84EFB6C', 'ADS', 'NASA Astrophysics Data System (ADS)', 'Hosted by NASA Astrophysics Data System (ADS)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AA9B968D', 'UKB', 'Dutch Library Consortium (UKB)', 'Hosted by Royal Library of the Netherlands', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AC0A709A', 'SciCrunch/ OBOFoundry', 'SciCrunch/ OBOFoundry', 'Hosted by SciCrunch/ OBOFoundry', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AC2A4892', 'protocols.io', 'protocols.io', 'Hosted by protocols.io', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AD794585', 'Getty Research Institute', 'Getty Research Institute', 'Hosted by Getty Research Institute', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AF2656BA', 'EIDR', 'Entertainment Identifier Registry Association (EIDR)', 'Hosted by Entertainment Identifier Registry Association (EIDR)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B95CFAD7', 'Wikimedia Foundation', 'Wikimedia Foundation', 'Hosted by Wikimedia Foundation', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BAA5FFF5', 'ITU', 'International Organisation for Standardization (ITU)', 'Hosted by International Organisation for Standardisation (ISO) and ITU', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C2D1F12A', 'W3C Permanent Identifier Community Group', 'W3C Permanent Identifier Community Group', 'Hosted by W3C Permanent Identifier Community Group', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D099FDF6', 'RAISE.eu', 'RAISE.eu', 'Hosted by RAISE.eu', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D25F46B9', 'Digital Science', 'Digital Science', 'Hosted by Digital Science', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D32D405B', 'Austrian Library Network', 'Austrian Library Network', 'Hosted by Austrian National Library', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D3F2554C', 'CrossRef', 'CrossRef', 'Hosted by CrossRef', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D7C1CB36', 'IUPAC', 'IUPAC', 'Hosted by International Union of Pure and Applied Chemistry (IUPAC)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DDE12023', 'DFG', 'German Research Foundation (DFG)', 'Hosted by German Research Foundation (DFG)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DE972BC0', 'GS1', 'GS1', 'Hosted by GS1', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E1983BC5', 'Ringgold, Inc.', 'Ringgold, Inc.', 'Hosted by Ringgold, Inc.', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E1BEACFF', 'NCBI', 'NCBI', 'Hosted by NCBI', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E2B3B6B1', 'ISAN', 'ISAN International Agency', 'Hosted by ISAN International Agency', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E61D9EA2', 'New Zealand Companies Office', 'New Zealand Companies Office', 'Hosted by New Zealand Companies Office', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:EB6E2A73', 'Swiss National Library', 'Swiss National Library', 'Hosted by Swiss National Library', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:EEC5A1B3', 'Internet Archive', 'Internet Archive', 'Hosted by Internet Archive', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F1A18DCC', 'German National Library', 'German National Library', 'Hosted by German National Library', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F1D2AA71', 'Statistics Finland', 'Statistics Finland', 'Hosted by Statistics Finland', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F2D38B3E', 'ISBN', 'ISNI International Agency', 'Hosted by ISNI International Agency', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F34A3E3D1', 'ISSN.org', 'ISSN International Centre', 'The CIEPS, also known as the ISSN International Centre, is an intergovernmental organization which manages at the international level the identification and the description of serial publications and ongoing resources, print and online, in any subject.', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F34A3E3D2', 'DONA', 'The DONA Foundation', 'We oversee the administration of the Global Handle Registry®. We also credential stakeholders from various countries as Multi-Primary Administrators, who can then use or enable others to use identifier and resolution services using the Handle System.', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F34A3E3D3', 'RoR', 'The Research Organisation Registry (ROR) is a global, community-led registry of open persistent identifiers for research organisations. ', 'ROR is a global, community-led registry of open persistent identifiers for research organisations. CDL, Crossref, DataCite manage RoR on behalf of the community', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F34A3E3D4', 'ORCID', 'ORCID, Inc.', 'Hosted by ORCID, Inc.', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F34A3E3D5', 'ARK Alliance', 'ARK Alliance Technical Working Group', 'Hosted by California Digital Library (CDL)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F34A3E3D6', 'ABES', 'ABES (Agence Bibliographique de l''Enseignement Supérieur)', 'Hosted by ABES (Agence Bibliographique de l''Enseignement Supérieur)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F34A3E3D8', 'arXiv.org', 'arXiv.org', 'Hosted by Cornell University', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F3EF0F30', 'EC', 'European Commission', 'Hosted by European Commission', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F8FB1B50', 'National Awareness Centre (Slovakia)', 'National Awareness Centre (Slovakia)', 'Hosted by National Awareness Centre (Slovakia)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F9F68E17', 'IFPI', 'International Federation of the Phonographic Industry (IFPI)', 'Hosted by International Federation of the Phonographic Industry (IFPI)', NULL, '0000-0002-0255-5101', '2025-02-04');
INSERT INTO k_Authority(IDAUT, lodAUT, AUT, labelAuthority, descAuthority, lodAUT_V, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:65D51A0IC', 'ICCU', 'ICCU - Istituto Centrale per il Catalogo Unico della Biblioteche Italiane per le informazioni bibliografiche', 'Italian Central Institute for Cataloguing and Documentation (ICCU)', NULL, '0000-0002-0255-5101', '2025-02-04');



