-- ------------------------------------------------
-- Version: v1.7
--
-- Description: Migration that introduces the scheme table
-- -------------------------------------------------

DROP TABLE k_Identifier;

CREATE TABLE k_Identifier (
    IDIDN integer,
    lodIDN character varying(255) NOT NULL,
    IDN character varying(255),
    labelIdentifier character varying(255),
    descIdentifier text,
    lodIND_V character varying(255),
    startDate timestamp with time zone,
    populatedBy character varying(255),
    lastTouch character varying(255),
    PRIMARY KEY (lodIDN)
);

INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:55673516', 'Book ID', 'Book ID', NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:075D8338X', 'Not Applicable', 'Not Applicable', 'No Identifier has been selected or indicated in relation to recommended use, or in other relationships in the Knowledge Base', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:075D8338', 'AID', 'AID', 'PubChem BioAssay contains small-molecule and RNAi screening data along with associated annotation information from contributing organizations. BioAssay contains a collection of bioactivity and toxicity data that has greatly supported research in fields such as medicinal chemistry, drug discovery, pharmaceutical genomics and informatics research. As a primary archive, the provenance of all records belongs to the submitter.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:15BEDB40', 'ARK', 'ARK', 'Multi-purpose persistent identifier for information objects of any type. Archival Resource Keys (ARKs) serve as persistent identifiers, or stable, trusted references for information objects. Among other things, they aim to be web addresses (URLs) that don’t return 404 Page Not Found errors. The ARK Alliance is an open global community supporting the ARK infrastructure on behalf of research and scholarship. End users, especially researchers, rely on ARKs for long term access to the global scientific and cultural record. Since 2001 some 8.2 billion ARKs have been created by over 1000 organizations — libraries, data centers, archives, museums, publishers, government agencies, and vendors. They identify anything digital, physical, or abstract. ARKs are open, mainstream, non-paywalled, decentralized persistent identifiers that can be created by an organization as soon as it is registered with a NAAN (Name Assigning Authority Number). Once registered, an ARK organization can create unlimited numbers of ARKs and publicize them via the n2t.net global resolver or via their own local resolver.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:03A715EA', 'arXiv', 'arXiv', 'Article identifier scheme used by arXiv. arXiv is an e-print service in the fields of physics, mathematics, non-linear science, computer science, and quantitative biology.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:03A715EA1', 'BibCode', 'BibCode', 'Bibliographic reference code for a journal, maintained by Harvard', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F00A6677', 'Bitbucket', 'Bitbucket', 'Bitbucket is a Git-based source code repository hosting service owned by Atlassian.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:88E37094', 'BusinessID', 'BusinessID', 'In Finland, a code given to businesses and organizations', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:27D128A4', 'CID', 'CID', 'PubChem Compound records are derived summaries that give users access to a rich set of related content. Compound records contain unique chemical structures extracted from contributed Substance records through a process called ‘standardization’. Each Compound record points to at least one Substance record.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B7EB7BAA', 'COL', 'COL', 'Identifier of a taxon or synonym in the Catalogue of Life', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A514F388', 'CONFIDENT', 'CONFIDENT', 'ConfIDent makes conferences and other formats of scientific events persistently accessible in high quality.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BDE0B4B7', 'CrossRef Funders', 'CrossRef Funders', 'The Funder Registry is an open registry of persistent identifiers for grant-giving organizations around the world.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BDE0B4B71', 'CrossRef Grant', 'CrossRef Grant', 'The Crossref Grant Linking System (GLS) is a service for research funders to contribute to open science infrastructure. As members of Crossref, funders create unique links and open metadata about their support of all kinds, from financial grants to prizes to use of facilities. ', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F12AD34E1', 'CURIE', 'CURIE', 'A data type whose purpose is specifically to allow for the definition of scoped names that map to URIs', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BDE0B4B72', 'DAI', 'DAI', 'A unique number to all academic authors in the Netherlands as a form of authority control', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:52A9C539', 'dbGaP ID', 'dbGaP ID', 'The database of Genotypes and Phenotypes (dbGaP) was developed to archive and distribute the data and results from studies that have investigated the interaction of genotype and phenotype in Humans.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:CB69320B', 'dbVar ID', 'dbVar ID', 'dbVar is NCBI''s database of human genomic Structural Variation — large variants >50 bp including insertions, deletions, duplications, inversions, mobile elements, translocations, and complex variants', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:998B7874', 'DCO-ID', 'DCO-ID', 'Digital object registration includes DCO-ID generation based on the global Handle System infrastructure and metadata collection using VIVO.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3E6F3EE6', 'DOI', 'DOI', 'The Digital Object Identifier System is for identifying content objects in the digital environment.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3E6F3EE61', 'DOI: Crossref', 'DOI: Crossref', 'One of the official Digital Object Identifier Registration Agencies of the International DOI Foundation', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D1BA9B24', 'dPID', 'dPID', 'DIDs  (dPIDs) are a new type of identifier that enables verifiable, self-sovereign digital identity using blockchain and DLT. DIDs are an effort by the W3C Credentials Community Group and the wider Internet identity community to define identifiers that can be registered, updated, resolved, and revoked without any dependency on a central authority or intermediary.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:025992EB', 'EAN13', 'EAN13', 'Standard describing a barcode symbology and numbering', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6081C2D5', 'EIDR', 'EIDR', 'Identifier for a film or television work, edit or manifestation, in the Entertainment Identifier Registry', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5AB84DF2', 'eISSN', 'eISSN', 'ISSN for an electronic publication', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3FA62023', 'ePIC', 'ePIC', 'The ePIC system is one of several MPAs based on the Handle System, and offers EU-based mirroring and resolution of handles.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8C3CC433', 'EU PIC', 'EU PIC', 'A Participant Identification Code (PIC) is a 9-digit number that serves as a unique identifier for legal entities participating in European funding programmes. A PIC number has no expiry date.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:10C00601', 'GDS ID', 'GDS ID', 'This database stores curated gene expression DataSets, as well as original Series and Platform records in the Gene Expression Omnibus (GEO) repository. Enter search terms to locate experiments of interest. DataSet records contain additional resources including cluster tools and differential expression queries.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B9A4AB49', 'Gene ID', 'Gene ID', 'Gene integrates information from a wide range of species. A record may include nomenclature, Reference Sequences (RefSeqs), maps, pathways, variations, phenotypes, and links to genome-, phenotype-, and locus-specific resources worldwide.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D800044E', 'Genome ID', 'Genome ID', 'This resource organizes information on genomes including sequences, maps, chromosomes, assemblies, and annotations.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B0DD2B6E', 'GEO ID', 'GEO ID', 'This database stores individual gene expression profiles from curated DataSets in the Gene Expression Omnibus (GEO) repository. Search for specific profiles of interest based on gene annotation or pre-computed profile characteristics.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C2BEAE03', 'GeoNames ID', 'GeoNames ID', 'Identifier in the GeoNames geographical database.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C2BEAE031', 'GePRIS', 'GePRIS', 'Identifies authors by the first 2-4 letters of their surname plus numbers (e.g. XX 1234 or YY 67) generated by Elektra, the DFG''s internal administrative grant-processing procedure. This disambiguation is for DFG''s internal processes only.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4A58E4401', 'GitHub', 'GitHub', NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4A58E4402', 'GitLab', 'GitLab', NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:77FF1083', 'GND', 'GND', 'Identifier for the German National Library', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:5CEA29B9', 'GRID', 'GRID', 'International coverage of the world''s leading research organisations, indexing 92% of funding allocated globally.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C6B514CF', 'HAL article ID', 'HAL article ID', 'identifier for an article in the HAL (Hyper Articles en Ligne) open access repository', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:73B0A225', 'Handle', 'Handle', 'Handle System identifier, which is a superset of the DOI', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:60F6C8F3', 'HomoloGene ID', 'HomoloGene ID', 'HomoloGene, a tool of the United States National Center for Biotechnology Information (NCBI), is a system for automated detection of homologs.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:962AFA12', 'ICD', 'ICD', 'The International Classification of Diseases is the international standard diagnostic classification for all general epidemiological and many health management purposes.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2EAAEA03', 'IdRef ID/SUDOC', 'IdRef ID/SUDOC', 'Identifier for authority control in the French collaborative library catalog (see
also P1025). Format: 8 digits followed by a digit or X', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0E85921A', 'IGSN', 'IGSN', 'IGSN is a globally unique and persistent identifier for material samples and specimens. IGSNs are obtained from IGSN e.V. Agents.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:83FC72F3', 'IMDb company ID', 'IMDb company ID', 'D for a company or organization listed in the Internet Movie Database', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DDB8E5B0', 'IMDb name ID', 'IMDb name ID', 'ID that characterize a person on Internet Movie Database', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9D46195A', 'IMDb title ID', 'IMDb title ID', 'ID that characterize a movie on Internet Movie Database', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6FA60579', 'InChI', 'InChI', 'The IUPAC International Chemical Identifier (InChI) is a non-proprietary identifier for chemical substances that can be used in printed and electronic data sources. It is derived solely from a structural representation of that substance, such that a single compound always yields the same identifier.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D2BC44A7', 'InChiKey', 'InChiKey', 'The IUPAC International Chemical Identifier (InChI, see MIR:00000383) is an identifier for chemical substances, and is derived solely from a structural representation of that substance. Since these can be quite unwieldly, particularly for web use, the InChIKey was developed. These are of a fixed length (25 character) and were created as a condensed, more web friendly, digital representation of the InChI.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8A464A0E', 'ISLRN', 'ISLRN', 'The International Standard Language Resource Number (ISLRN) is a new, unique and universal identification schema for Language Resources which provides Language Resources with unique names using a standardized nomenclature. It also ensures Language Resources are identified, and consequently recognized with proper references in activities within Human Language Technologies, as well as in documents and scientific papers.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:59B443C3', 'JuFo-id', 'JuFo-id', 'Identifier in the Julkaisufoorumi (Finnish Publication Forum)', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E1F68A70', 'Korean national author ID', 'Korean national author ID', 'The Korean National Author ID system is an identifier used in South Korea to uniquely identify authors, particularly those involved in academic and scholarly publishing.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:487BCE7F', 'Korean national research ID', 'Korean national research ID', NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:56ADD30B', 'Korean research funding ID', 'Korean research funding ID', NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:016841FF', 'LCCN', 'LCCN', 'Library of Congress name authority (persons, families, corporate bodies, events, places, works and expressions) and subject authority identifier', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7D9E4E44', 'Magnet', 'Magnet', 'Magnet is a URI scheme that defines the format of magnet links, a de facto standard for identifying files (URN) by their content, via cryptographic hash value rather than by their location.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:B36773C9', 'MeSH ID        ', 'MeSH ID        ', 'MeSH (Medical Subject Headings) is the NLM controlled vocabulary thesaurus used for indexing articles for PubMed.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:FE96C149', 'MMDB-ID', 'MMDB-ID', 'The Conserved Domain Database (CDD) brings together several collections of multiple sequence alignments representing conserved domains, in addition to NCBI-curated domains that use 3D-structure information explicitly to define domain boundaries and provide insights into sequence/structure/function relationships.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6AAA1ABD', 'RoR', 'RoR', 'ROR (Research Organization Registry) is a global, community-led registry of open persistent identifiers for research organizations. ROR is jointly operated by California Digital Library, Crossref, and Datacite.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:50E7B5FE', 'NLM Catalog ID        ', 'NLM Catalog ID        ', 'The NLM Catalog provides access to NLM bibliographic data for journals, books, audiovisuals, computer software, electronic resources and other materials. Links to the library''s holdings in LocatorPlus, NLM''s online public access catalog, are also provided.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AF81E099', 'Nucleotide GI number', 'Nucleotide GI number', 'The Nucleotide database is a collection of sequences from several sources, including GenBank, RefSeq, TPA and PDB. Genome, gene and transcript sequence data provide the foundation for biomedical research and discovery.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F8110591', 'NZBN', 'NZBN', 'The NZBN (New Zealand Business Number) is a unique identifier assigned to businesses and other organisations in New Zealand. ', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AB1807F6', 'OCLC Control Number', 'OCLC Control Number', 'OCLC assigns a unique number to each bibliographic record input into WorldCat.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:08EE6DB9', 'OMID', 'OMID', 'Every entity in OpenCitations Meta (https://opencitations.net/meta) is assigned persistent internal identifier called OpenCitations Meta Identifier (OMID). The OMID has structure [[entity_type_abbreviation]]/[[supplier_prefix]][[sequential_number]]. For example, the first journal article ever processed has OMID br/0601 (the full URI is https://w3id.org/oc/meta/br/0601), where br is the abbreviation of bibliographic resource, and 060 corresponds to the supplier prefix, helpful in recognising at a glance the index it belongs to (i.e., OpenCitations Meta). Finally, 1 indicates that this is the index''s first bibliographic resource ever minted.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:6AE88038', 'OpenCitations Corpus', 'OpenCitations Corpus', 'The OpenCitations Corpus is open repository of scholarly citation data made available under a Creative Commons public domain dedication (CC0), which provides accurate bibliographic references harvested from the scholarly literature that others may freely build upon, enhance and reuse for any purpose, without restriction under copyright or database law.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9C827E94', 'OpenURL', 'OpenURL', 'An OpenURL is similar to a web address, but instead of referring to a physical website, it refers to an article, book, patent, or other resource within a website', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:152D5274', 'ORCID', 'ORCID', 'ORCID (Open Researcher and Contributor ID) is an open, non-profit, community-based effort to create and maintain a registry of unique identifiers for individual researchers. ORCID records hold non-sensitive information such as name, email, organization name, and research activities.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:152D52741', 'PIC', 'PIC', 'The PIC is a unique identifier for your organisation that is used to track and manage participants in EU-funded programs, projects, and initiatives', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:152D52742', 'PIDINST', 'PIDINST', NULL, NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D8E9EA2D', 'PMCID', 'PMCID', 'PubMed Central® (PMC) is a free full-text archive of biomedical and life sciences journal literature at the U.S. National Institutes of Health''s National Library of Medicine (NIH/NLM)', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:08629E50', 'PMID', 'PMID', 'A PMID (PubMed identifier or PubMed unique identifier) is a unique integer value, starting at 1, assigned to each PubMed record.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AE530285', 'PopSet ID', 'PopSet ID', 'The PopSet database is a collection of related DNA sequences derived from population, phylogenetic, mutation and ecosystem studies that have been submitted to GenBank.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D0FEC2B9', 'Probe ID	', 'Probe ID	', 'The NCBI Probe Database is a public registry of nucleic acid reagents designed for use in a wide variety of biomedical research applications, together with information on reagent distributors, probe effectiveness, and computed sequence similarities.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:A2F84B54', 'Protein Cluster ID', 'Protein Cluster ID', 'This collection of related protein sequences (clusters) consists of proteins derived from the annotations of whole genomes, organelles and plasmids. It currently limited to Archaea, Bacteria, Plants, Fungi, Protozoans, and Viruses', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4A58E440', 'Protein GI number        ', 'Protein GI number        ', 'The Protein database is a collection of sequences from several sources, including translations from annotated coding regions in GenBank, RefSeq and TPA, as well as records from SwissProt, PIR, PRF, and PDB. Protein sequences are the fundamental determinants of biological structure and function.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:187B413B', 'PSSM-ID', 'PSSM-ID', 'CDD is a protein annotation resource that consists of a collection of well-annotated multiple sequence alignment models for ancient domains and full-length proteins.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D75629BE', 'PURL', 'PURL', 'A PURL is a Persistent Uniform Resource Locator', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:335BCBF1', 'QID', 'QID', 'Unique identifier (UID) used in Wikidata', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:52184C71', 'QID / WDQID', 'QID / WDQID', 'Wikidata is a collaboratively edited knowledge base operated by the Wikimedia Foundation. It is intended to provide a common source of certain types of data which can be used by Wikimedia projects such as Wikipedia. Wikidata functions as a document-oriented database, centred on individual items. Items represent topics, for which basic information is stored that identifies each topic.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:335BCBF11', 'RAI ID', 'RAI ID', 'Research Analysis Identifier (RAI) of experiments will become a new Persistent Identifier (PID) that can be used in addition to existing PIDs. This identifier combines the result with the dataset and algorithm employed by a researcher to process the dataset.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:0D27745F', 'RAID', 'RAID', 'A unique and persistent identifier for research projects', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8FDADD4C', 're3data', 're3data', 'Re3data is a global registry of research data repositories that covers research data repositories from different academic disciplines.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:47118C40', 'ResearcherID', 'ResearcherID', 'ResearcherID is an identifying system for scientific authors. The system was introduced in January 2008 by Thomson Reuters Corporation.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1F0B6419', 'RIN', 'RIN', 'A commercial protocol sharing tool, which allows scientists to check in protocols the way that computer scientists check in code', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:42740FD8', 'Ringgold ID', 'Ringgold ID', 'Identifier for organisations in the publishing industry supply chain', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:D9D0AD30', 'rs number', 'rs number', 'dbSNP contains human single nucleotide variations, microsatellites, and small-scale insertions and deletions along with publication, population frequency, molecular consequence, and genomic and RefSeq mapping information for both common variations and clinical mutations.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:986D97DF', 'SBN/ ICCU', 'SBN/ ICCU', 'identifier issued by National Library Service (SBN) of Italy', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:109F4044', 'ScopusAuthorID', 'ScopusAuthorID', 'Identifier for an author assigned in Scopus bibliographic database', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C9B802B5', 'SF-edu-ID', 'SF-edu-ID', 'The Register of educational institutions is a chargeable product of Statistics Finland containing the addresses of all educational institutions in Finland. The Register is updated yearly in the spring. The Register contains data collected 2023.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8930C278', 'SID', 'SID', 'PubChem Substance is the primary archive for community-provided information about chemical entities.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:22104FE0', 'SRA ID	', 'SRA ID	', 'Sequence Read Archive (SRA) data, available through multiple cloud providers and NCBI servers, is the largest publicly available repository of high throughput sequencing data. The archive accepts data from all branches of life as well as metagenomic and environmental surveys. SRA stores raw sequencing data and alignment information to enhance reproducibility and facilitate new discoveries through data analysis.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8A580D4C', 'SWHID', 'SWHID', 'Persistent identifier of a software source code artifact as archived in the Software Heritage Archive', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:1D9178F5', 'TaxID', 'TaxID', 'The Taxonomy Database is a curated classification and nomenclature for all of the organisms in the public sequence databases. This currently represents about 10% of the described species of life on the planet.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C454BB2B', 'Toolkit ID', 'Toolkit ID', 'The NCBI C++ Toolkit is a public-domain collection of portable libraries, consisting of a cross-platform application framework and a set of utilities and supporting classes to work with biological data.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BFEB0A72', 'UPC', 'UPC', 'Barcode symbology used for tracking trade items in stores', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:F12AD34E', 'URI', 'URI', 'String of characters used to identify a name of a resource on a network such as the internet', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:208E9775', 'URL', 'URL', 'A uniform resource locator (URL), colloquially known as an address on the Web, is a reference to a resource that specifies its location on a computer network and a mechanism for retrieving it', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E775ECFD', 'URN', 'URN', 'Uniform Resource Identifier (URI) that uses the urn scheme', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:DE9F6BF4', 'URN:ISAN', 'URN:ISAN', 'International Standard Audiovisual Number (ISAN) is a unique identifier for audiovisual works and related versions, similar to ISBN for books', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:52EBCE9D', 'URN:ISBN', 'URN:ISBN', 'The International Standard Book Number (ISBN) is for identifying printed books.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4502C312', 'URN:ISMN', 'URN:ISMN', 'identifier for printed music (not in book form) developed by ISO. ', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7EBD4614', 'URN:ISRC', 'URN:ISRC', 'international standard code for uniquely identifying sound recordings and music video recordings', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9FF848E5', 'URN:ISSN', 'URN:ISSN', 'The International Standard Serial Number (ISSN) is a unique eight-digit number used to identify a print or electronic periodical publication, rather than individual articles or books.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:92768060', 'URN:ISTC', 'URN:ISTC', 'Unique identifier for text-based works', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:774111F8', 'URN:LSID', 'URN:LSID', 'Life Science Identifiers are a way to name and locate pieces of information on the web. Essentially, an LSID is a unique identifier for some data, and the LSID protocol specifies a standard way to locate the data (as well as a standard way of describing that data)', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7E709E59', 'URN:NBN', 'URN:NBN', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:68ADD24A', 'URN:NBN:AT', 'URN:NBN:AT', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7E709E591', 'URN:NBN:CH', 'URN:NBN:CH', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:369FA36F', 'URN:NBN:CZ', 'URN:NBN:CZ', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7E709E592', 'URN:NBN:DE', 'URN:NBN:DE', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7E709E593', 'URN:NBN:FI', 'URN:NBN:FI', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C8042C4B', 'URN:NBN:HR', 'URN:NBN:HR', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:9A92E859', 'URN:NBN:HU', 'URN:NBN:HU', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:4EA08A5A', 'URN:NBN:IT', 'URN:NBN:IT', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7E709E594', 'URN:NBN:NL', 'URN:NBN:NL', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:8EB6C97D', 'URN:NBN:NO', 'URN:NBN:NO', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:882397A9', 'URN:NBN:SE', 'URN:NBN:SE', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:E20D377D', 'URN:NBN:SI', 'URN:NBN:SI', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7380A573', 'URN:NBN:SK', 'URN:NBN:SK', 'National Bibliography Number (NBN) is a group of publication identifier systems used by national libraries in countries such as Germany, Italy, Finland, Norway, The Netherlands and Sweden', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C2989F23', 'URN:OID', 'URN:OID', 'OIDs provide a persistent identification of objects based on a hierarchical structure of Registration Authorities (RA), where each parent has an object identifier and allocates object identifiers to child nodes.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3DA72078', 'VAT number', 'VAT number', 'Identifier of person or company, used for value added tax purposes', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7D3DC0E1', 'VIAF', 'VIAF', 'Identifier for the Virtual International Authority File database [format: up to 22 digits]', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7C278907', 'Virta-id', 'Virta-id', 'The Virta-ID is associated with the VIRTA Higher Education Achievement Register (VIRTA-opintotietopalvelu) in Finland. This service was built as part of the Raketti project during 2012 and 2013 and officially launched in 2014. It serves as a national data repository for Finnish higher education institutions, aiming to improve student admissions and facilitate various administrative and academic processes.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:7725DE2B', 'W3ID', 'W3ID', 'Secure, permanent URLs for your Web application that will stand the test of time.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:BE0AA447', 'Wikipedia', 'Wikipedia', 'Wikipedia is a multilingual, web-based, free-content encyclopedia project based on an openly editable model. It is written collaboratively by largely anonymous Internet volunteers who write without pay.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:AC2CDAA9', 'WOS', 'WOS', 'Unique academic work identifier assigned in Web of Science bibliographic database (Web of Science Core Collection only and do not include WOS: prefix)', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:C7CE618B', 'XRI', 'XRI', 'An Extensible Resource Identifier (abbreviated XRI) is a scheme and resolution protocol for abstract identifiers compatible with Uniform Resource Identifiers and Internationalized Resource Identifiers, developed by the XRI Technical Committee at OASIS', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:2E591E66', 'Z39.88-2004', 'Z39.88-2004', 'The National Information Standards Organization (NISO) has developed standards for OpenURL and its data container as American National Standards Institute (ANSI) standard ANSI/NISO Z39.88-2004', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:710BC55E', 'URN:ISNI', 'URN: ISNI', '16-digit identifier for people and organisations
ISNI is the ISO certified global standard number for identifying the millions of contributors to creative works and those active in their distribution, including researchers, inventors, writers, artists, visual creators, performers, producers, publishers, aggregators, and more. It is part of a family of international standard identifiers that includes identifiers of works, recordings, products and right holders in all repertoires, e.g. DOI, ISAN, ISBN, ISRC, ISSN, ISTC, and ISWC. The mission of the ISNI International Authority (ISNI-IA) is to assign to the public name(s) of a researcher, inventor, writer, artist, performer, publisher, etc. a persistent unique identifying number in order to resolve the problem of name ambiguity in search and discovery; and diffuse each assigned ISNI across all repertoires in the global supply chain so that every published work can be unambiguously attributed to its creator wherever that work is described.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
INSERT INTO k_Identifier (IDIDN, lodIDN, IDN, labelIdentifier, descIdentifier, lodIND_V, STartDate, populatedBy, lastTouch) VALUES (NULL, 'pid_graph:3E6F3EE62', 'DOI: DataCite', 'DOI: DataCite', 'The global consortium DataCite was established in 2009 to overcome the challenges of data citation. The aim of the consortium is to establish easy access to data, to increase the acceptance of data publication and to support data archiving.', NULL, NULL, '0000-0002-0255-5101', '30/01/2024');
